### ISSUE TITLE
Question about `com.google.android.configupdater`

### ISSUE THREAD

**Issue by Obegg** [Universal-Debloater-Alliance/universal-android-debloater-next-generation#106]
I have a question about `com.google.android.configupdater`.
```
  {
    "id": "com.google.android.configupdater",
    "list": "Google",
    "description": "ConfigUpdater\nOccasionally runs in the background.\nAuto updates certificates for TLS connection, firewall configuration, e.t.c.\nMainly used for Google services? Might be fine to disable if you don't use Google services. Disabling might mess with security if you do use them though.\nhttps://android.googlesource.com/platform/frameworks/base/+/master/core/java/android/os/ConfigUpdate.java",
    "dependencies": [],
    "neededBy": [],
    "labels": [],
    "removal": "Recommended"
  },
  ```
This is marked as `Recommended` but the description mentions "certificates for TLS connection, firewall configuration, e.t.c", so maybe it should not be marked as `Recommended`?

**Comment by Blitz517** [comment]
Its only for google play services updates, not needed

**Comment by AnonymousWP** [comment]
I agree it should be `Advanced` instead. Most users (even UAD users I believe) use Google Services. Therefore the package might be needed. What do you think @Obegg @Blitz517?

**Comment by Frigyes06** [comment]
I could not find which PR did this, git blame got obliterated by hashmap PR
