### ISSUE TITLE
Change default theme from `Lupin` to `Dark`

### ISSUE THREAD

**Issue by Obegg** [Universal-Debloater-Alliance/universal-android-debloater-next-generation#122]
**Describe the feature you want**
Default theme should be `Dark` and not `Lupin`.

**Comment by AnonymousWP** [comment]
> **Describe the feature you want** Default theme should be `Dark` and not `Lupin`.

Please explain *why* it should be that colour.

**Comment by AnonymousWP** [comment]
I created a poll for users to vote: https://github.com/Universal-Debloater-Alliance/universal-android-debloater/discussions/123

**Comment by allanonmage** [comment]
I don't mind that nowadays people prefer dark themes to the classic default (now known as light themes).  BUT FOR THE LOVE OF ALL THAT IS HOLY, stop trying to make my eyes bleed with the INSANE "light" themes that you are coming up with.  You literally have 50 years of exampls to understand how to make a light themed software without making users' eye's bleed.

Your light theme is such a light theme, and your dark theme is almost as bad, so I use the purple one.

**Comment by Frigyes06** [comment]
Lupin is not that light. I prefer it because the dark mode is kinda ugly right now lol
