### ISSUE TITLE
Guide to extract packages

### ISSUE THREAD

**Issue by Obegg** [Universal-Debloater-Alliance/universal-android-debloater-next-generation#127]
**Describe the feature you want**
Add a guide or something that will teach users how to extract packages.
I was requested to extract packages but I did not know how, you did not guide me, so maybe add a guide for other users.

Download adb from here https://developer.android.com/tools/adb unzip it and open cmd in there
Enable developer options (Settings > about > 4 taps on build info)
Enable Wireless ADB debugging (if you don't want to use cable from phone to PC)
Enable USB debugging
in the cmd you opened before type `adb devices` or `adb connect IP` (IP = device ip)
example: `adb connect 192.168.1.10`
now accept the pop-up in your device

note: if you only connected to one device there's no need to keep using `-s 192.168.1.10`

to list all the packages on the phone use `adb -s 192.168.1.10 shell pm list packages`
let's say there's a package you need to extract, use `adb -s 192.168.1.10 shell pm path com.test`
and you get something like `package:/odm/overlay/test.apk`
you delete the `package:` and copy the rest `/odm/overlay/test.apk`
now you take the apk from the device by `adb -s 192.168.1.10 pull /odm/overlay/test.apk`
and now you have the apk file on your PC.

**Comment by allanonmage** [comment]
I came from the original, figured out the new Rusty version, then tried to figure out why it was having an issue, then found this project, and now the UI flow is different and you don't use the same config file, and there is no INTUITIVE way to load a config file, and nothing is working.

Make a simple user guide on how to use your software.  You went through all that effort to make it, take 5 minus to give instructions for it.

**Comment by Frigyes06** [comment]
@Obegg Would you be okay with this guide in the Wiki, and a link to the wiki in an appropriate place in the readme?

**Comment by Frigyes06** [comment]
@Obegg Sorry, bad phrasing. What I meant is would having a guide in the wiki as opposed to the README be an acceptable solution?

**Comment by Frigyes06** [comment]
Yeah, totally. We'll do it like that then.

**Comment by AnonymousWP** [comment]
Sorry that this took so long! Thanks for your step-by-step guide. Because Wireless ADB does not seem to work (a user reported this yesterday) with UAD-ng, I copied it without the Wireless ADB part.

https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation/wiki/How-to-contribute#extracting-packages

**Comment by AnonymousWP** [comment]
Done: https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation/wiki/How-to-contribute/_compare/69957125cdd6a103ab13b4983b47cc8c1ab06f5f...bc6ff86b6ac168d13271dd66e337231345358f7c
