### ISSUE TITLE
Don't use %APPDATA%

### ISSUE THREAD

**Issue by allanonmage** [Universal-Debloater-Alliance/universal-android-debloater-next-generation#128]
**Describe the bug**
You are using bloatware tactics in your bloatware removal tool.  Use the working directory, not APPDATA.  Your program doesn't install anything, so there's no reason anyone would expect you to use APPDATA, nor go looking in APPDATA for anything.  APPDATA is, itself, bloat, which is why I am explaining this so simply and curtly, so that whatever went backwards in your brain, can get un-backwards'd.  APPDATA = BAD.

**Expected behavior**
No bloatware in a bloatware removal tool.  Use the working directory, not APPDATA.

**You have a solution?**
Use the working directory, not APPDATA.

**UAD log**
N/A

**Comment by Frigyes06** [comment]
Persistent folders follow the location of [the standards of the different OS](https://github.com/dirs-dev/dirs-rs#example)
