### ISSUE TITLE
UI: add logo

### ISSUE THREAD

**Issue by Obegg** [Universal-Debloater-Alliance/universal-android-debloater-next-generation#148]
**Describe the feature you want**
Currently UAD has no logo:
![image](https://github.com/Universal-Debloater-Alliance/universal-android-debloater/assets/13978119/8ace200a-05a6-4cf1-be95-f33f834b2bd6)
It would be nice to see a logo.

**Comment by Frigyes06** [comment]
We'd need a logo first

**Comment by AnonymousWP** [comment]
See https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation/discussions/164.
