### ISSUE TITLE
unloading android.packageinstaller caused rescueparty to fire up

### ISSUE THREAD

**Issue by Jopp-gh** [Universal-Debloater-Alliance/universal-android-debloater-next-generation#157]
**Your phone model**:
motorola e40 (cyprus)

**Describe the issue**
after unloading `com.google.android.packageinstaller`, this phone isnt able to boot anymore and brings up the `rescueparty` command to wipe all phone data to fakktory defaults. Hate motorola for making it super-difficult to flash this phone, wont pick this brand anymore thats sure. I used your debloater with success for a longer time, yesterday i did it wrong- since I use another package manager and other marketplaces to update apps, I thought it is fine to unload the preinstalled packageinstaller. Please see the log at the bottom

**You have a solution?**
The point is, adb or the commands integrated in your app are unable to detect my model - it should be possible to add my phone model manually and restore everything to default settings from my computer. Probably Debloaters commands are not powerful enough to modify phone settings during boot or in recovery mode. But exactly this can happen if the wrong settings are ticked and you restart your phone. 

To prevent such accidents, 
first and foremost:
exclude `com.google.android.packageinstaller` because it breaks a phone
second:
not sure if possible but add some test-mechanism to simulate if debloaters new settings are  really healthy for a phone.

**UAD-ng log**
```
2024-01-04 10:54:28 WARN  [src/core/uad_lists.rs:218] Could not load remote debloat list: https://raw.githubusercontent.com/0x192/universal-android-debloater/main/resources/assets/uad_lists.json: Dns Failed: resolve dns name 'raw.githubusercontent.com:443': failed to lookup address information: nodename nor servname provided, or not known
2024-01-04 11:03:27 INFO  [src/core/utils.rs:222] [Expert] pm uninstall --user 0 com.google.android.packageinstaller -> Success
2024-01-04 11:08:12 INFO  [src/core/utils.rs:222] [Advanced] pm uninstall --user 0 com.google.android.ims -> Success
```

**Comment by Blitz517** [comment]
Before uninstalling read if its recommended or unsafe because this app is unsafe so better check recommended and advanced packages, alternatively expert if you want.

**Comment by Blitz517** [comment]
If you dont have com.android.packageinstaller app then its not safe

**Comment by Blitz517** [comment]
List all shows all apps but unsafe apps uninstall button is disabled.
About packageinstaller app:
Its weird, only on xiaomi miui china i have seen disabled stock packageinstaller and enabled com.miui.packageinstaller. Myabe try disable instead removing this app? It looks still unsafe btw.

**Comment by AnonymousWP** [comment]
Uhh? Unload? You mean disable? Disabling is something you need to explicitly enable in the settings.

What do you want us to do now exactly? I'm slightly confused.

**Comment by AnonymousWP** [comment]
@Jopp-gh Please follow-up on this.

**Comment by schbrns** [comment]
The package is already set to `Unsafe`.

A "health-check" isn't feasible due to the nature of varying devices and varying OS versions and sub-versions.
There is no way for us to know exactly, as we don't have exact `Unsafe` reasoning for every single device, just whatever has been crowdsourced thus far.
