### ISSUE TITLE
New packages

### ISSUE THREAD

**Issue by Skizzy24** [Universal-Debloater-Alliance/universal-android-debloater-next-generation#169]
**Packages:**

```
com.samsung.android.mtp
com.samsung.android.sm_cn
...
```
## Document each package the best you can

**List**: `Google`|`Misc`|`OEM` (manufacturer)|`AOSP`|`Pending`|`Carrier` (isp).

**Removal**:

- Recommended -- Pointless or outright negative packages, and/or apps available through Google Play.
- Advanced -- Breaks obscure or minor parts of functionality, or apps that aren't easily enabled/installed through Settings/Google Play. This category is also used for apps that are useful (default keyboard/gallery/launcher/music app.) but that can easily be replaced by a better alternative.
- Expert -- Breaks widespread and/or important functionality, but nothing important to the basic operation of the operating system. Removing an Expert package should not bootloop the device (unless mentioned in the description) but we can't guarantee it 100%.
- Unsafe -- Can break vital parts of the operating system. Removing an Unsafe package have an extremely high risk of bootlooping your device.

### \<App MTP\>

**List**: \<OEM\>
**Removal**: \<Expert\>

> If removed breaks MTP; you can't longer transfer files using your PC

### \<Smart Manager\>

**List**: \<OEM\>
**Removal**: \<Expert\>

> Device care but in chinese samsung phones, is different from global, could break some important functions if removed.

**Comment by AnonymousWP** [comment]
I think you broke the template, as some stuff is missing. You can remove placeholders.

**Comment by Skizzy24** [comment]
> I think you broke the template, as some stuff is missing. You can remove placeholders.

i removed some things on purpose

**Comment by AnonymousWP** [comment]
Yes but you should remove things as part of the template. And where's the checkbox for "I removed these packages from my phone" for example?

**Comment by Skizzy24** [comment]
> Yes but you should remove things as part of the template. And where's the checkbox for "I removed these packages from my phone" for example?

Cant you just update the list with what i provided? btw yes i uninstalled these packages.
