### ISSUE TITLE
send `adb kill-server` when user exit the app

### ISSUE THREAD

**Issue by Obegg** [Universal-Debloater-Alliance/universal-android-debloater-next-generation#177]
**Describe the feature you want**
send a `adb kill-server` command to the phone via ADB when user exit the app therefor will close the process `adb.exe` from remaining open while app is not used.

**Comment by prakharb5** [comment]
If not as a default setting, keeping it as an option in setting would be great!

**Comment by AnonymousWP** [comment]
Duplicate of https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation/issues/67.
