### ISSUE TITLE
Load external uad_lists.json file

### ISSUE THREAD

**Issue by fritolays** [Universal-Debloater-Alliance/universal-android-debloater-next-generation#180]
**Describe the feature you want**
Ability to load an external uad_lists.json file.
Doesn't even need any gui stuff just have it look for a uad_lists.json file in the same directory as uad_gui on load.
Would allow people to share/make/backup their lists.

**Comment by AnonymousWP** [comment]
Hmm? Why did you open and close the issue?

**Comment by fritolays** [comment]
Saw that someone else requested essentially the same thing.
