### ISSUE TITLE
infinite error logs if adb isn't installed

### ISSUE THREAD

**Issue by jxdv** [Universal-Debloater-Alliance/universal-android-debloater-next-generation#188]
**Describe the bug**
If adb isn't installed than 2 errors are logged infinitely. (UAD-ng version 0.6.2.)
![Screenshot from 2024-01-26 16-47-13](https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation/assets/138708600/96a270ff-de0d-45cf-83b1-775b7ba97c33)

**Expected behavior**
If adb isn't installed than logs the 2 error once and exit with error code 1.

**You have a solution?**
Exit right away if adb isn't installed.

**Comment by AnonymousWP** [comment]
One of our devs should look into this. Or, if you can help us out, file a PR.

**Comment by jxdv** [comment]
> One of our devs should look into this. Or, if you can help us out, file a PR.

I am not familiar with Rust, so I'd rather not do it myself, but it looks like an easy fix of exiting the process with code 1 if this error gets caught.
```rust
match command.output() {
    Err(e) => {
        error!("ADB: {}", e);
        Err("ADB was not found".to_string())
}
