### ISSUE TITLE
1 persistent nonexisting package in review selection window

### ISSUE THREAD

**Issue by prakharb5** [Universal-Debloater-Alliance/universal-android-debloater-next-generation#190]
**Describe the bug**

![image](https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation/assets/51435948/eceeee57-f969-4d8e-86c5-7085d1e57ad7)

I have only selected one package. But it is counted twice in 2 separate categories.
The selected package is from Recommended category.

![image](https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation/assets/51435948/d8fc0c0c-d502-4b0b-86c2-2fd0d0f907d7)

Selecting one package in Advanced category shows up as 2 packages in Advanced category.

**Expected behavior**
No error in enumeration

**You have a solution?**
NA

**UAD-ng log**
Upload the logfile generated by UAD-ng.

**Comment by prakharb5** [comment]
Restarting the app somehow fixed it, and now I cannot reproduce this bug :/

**Comment by AnonymousWP** [comment]
Add a comment in this issue if you can reproduce it, then I'll re-open it. Closing it for now.
