### ISSUE TITLE
com.huawei.multimedia.audioengine - wrong description

### ISSUE THREAD

**Issue by kyoforkshomebrews** [Universal-Debloater-Alliance/universal-android-debloater-next-generation#195]
**Your phone model**: POT_LX1

**Packages documentation to update:**

```
com.huawei.multimedia.audioengine
```

## Documentation Change

**List**: `Google`|`Misc`|`OEM` (manufacturer)|`AOSP`|`Pending`|`Carrier` (isp).

**Removal**:

- Recommended -- Pointless or outright negative packages, and/or apps available through Google Play.
- Advanced -- Breaks obscure or minor parts of functionality, or apps that aren't easily enabled/installed through Settings/Google Play. This category is also used for apps that are useful (default keyboard/gallery/launcher/music app.) but that can easily be replaced by a better alternative.
- Expert -- Breaks widespread and/or important functionality, but nothing important to the basic operation of the operating system. Removing an Expert package should not bootloop the device (unless mentioned in the description) but we can't guarantee it 100%.
- Unsafe -- Can break vital parts of the operating system. Removing an Unsafe package have an extremely high risk of bootlooping your device.

### com.huawei.multimedia.audioengine

**List**: Oem :arrow_right: Oem
**Removal**: Recommended
:arrow_right: Recommended

### Current description

> HwAssetSync? AppGallery updates? its needed for hisync problably?\nIts for Huawei Mobile services? it have in code analytics and assistant so its for spying.

### Proposed description

> Audio Engine, probably not needed. https://developer.huawei.com/consumer/en/audioengine

The current description is wrong. This has nothing to do with HwAssetSync

**Comment by AnonymousWP** [comment]
Wouldn't you argue it's for analytical purposes and thus for data collection?
