### ISSUE TITLE
Move most documentation to wiki

### ISSUE THREAD

**Issue by lavafroth** [Universal-Debloater-Alliance/universal-android-debloater-next-generation#205]
The goal is to keep a minimal README with the following:
- Screenshots
- Link to the wiki
- Discord link
- Funding

The rest of the documentation can move to the wiki.

_Originally posted in https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation/issues/186#issuecomment-1913115275_

**Comment by AnonymousWP** [comment]
Fixed with https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation/pull/210.
