### ISSUE TITLE
bug: uad-ng doesn't start if not executed as administrator

### ISSUE THREAD

**Issue by AnonymousWP** [Universal-Debloater-Alliance/universal-android-debloater-next-generation#221]
**Describe the bug**

When trying to launch UAD-ng, it's not starting unless you launch it as administrator.

**Expected behavior**

I expect it to launch even though it's not running as admin. This issue did not happen before.

**You have a solution?**

Nope.

**UAD-ng log**

Log doesn't return anything useful.

**Comment by Frigyes06** [comment]
Cannot reproduce

**Comment by AnonymousWP** [comment]
You tested on Windows?

**Comment by Frigyes06** [comment]
> You tested on Windows?

Yes. Dual boot system

**Comment by AnonymousWP** [comment]
Hmm, no idea what caused it, but works fine now. Closing it as I can't reproduce it. Perhaps it was a 0.x.x to 1.x.x thingy.
