### ISSUE TITLE
bug(update-check): when downloading an update failed, UAD-ng isn't verbose about it

### ISSUE THREAD

**Issue by AnonymousWP** [Universal-Debloater-Alliance/universal-android-debloater-next-generation#225]
**Describe the bug**

When using the built-in updater, it says it's downloading the update, but in fact nothing is happening.

**Expected behavior**

I expect it to be successful and if not, notify me what went wrong.

**You have a solution?**

No.

**UAD-ng log**

It's just stuck on

```
2024-02-07 19:55:55 DEBUG [src\core\update.rs:174] Checking for UAD update
2024-02-07 19:55:57 DEBUG [src\gui\mod.rs:266] UAD update has been download!
2024-02-07 19:55:57 ERROR [src\gui\mod.rs:305] Failed to update UAD!
```

**Comment by Frigyes06** [comment]
CI is broken, making bad files, not an issue with the actual program

**Comment by AnonymousWP** [comment]
> CI is broken, making bad files, not an issue with the actual program

Yeah, but then I expect it to return an error or message at least. This is too vague and it needs to be verbose.
