### ISSUE TITLE
One UI packages

### ISSUE THREAD

**Issue by Skizzy24** [Universal-Debloater-Alliance/universal-android-debloater-next-generation#231]
**Your phone model: A53**

**Packages:**

```
com.samsung.android.emergency
com.samsung.android.privacydashboard
com.samsung.memorysaver
com.samsung.android.app.smartwidget
```

- [x] **I removed all those packages on my phone**
   
### \<Emergency SOS\>

**List**: \<OEM\>
**Removal**: \<Advanced\>

> Has a lot of permissions, lets you send SOS messages and calls.

### \<Permission usage\>

**List**: \<OEM\>
**Removal**: \<Advanced\>

> Privacy dashboard in settings: https://insights.samsung.com/2023/08/17/what-is-privacy-dashboard-and-how-does-it-protect-my-data-2/

### \<Memory booster\>

**List**: \<OEM\>
**Removal**: \<Recommended\>

> "Helps you to free space" by letting you deleting duplicates and move contents and apps on a SD.

### \<Smart widget\>

**List**: \<OEM\>
**Removal**: \<Advanced\>

> Lets you group widgets on One UI 4, really an useful feature why should you uninstall it?

**Comment by AnonymousWP** [comment]
I don't agree with some of the `removal`s, so I'm changing some, see PR.
