### ISSUE TITLE
[Question] Maintainers | Project name?

### ISSUE THREAD

**Issue by Obegg** [Universal-Debloater-Alliance/universal-android-debloater-next-generation#24]
The original [UAD](https://github.com/0x192/universal-android-debloater) seems to have only one maintainer, which was the owner,
as a result - when the owner became unactive, so does the project.

Why not "bullet-proof" this revival project and add a couple of maintainers?

On the same breath - why not rename this project to "V2" or something like that? or add a prefix like "Re" (same way YouTube ReVanced did) in order to difference this project from the original one (and actually making this project easy to reach from a simple Google Search).

**Comment by Frigyes06** [comment]
Hello! Good questions!

Maintainers:
If I see someone is responsible and knows what they're doing, I'd be happy to add them as maintainers. Currently I see none.

Name:
I was thinking of rebranding to UADng for Next Generation? Will probably do so at release.
