### ISSUE TITLE
SVCAgent

### ISSUE THREAD

**Issue by Skizzy24** [Universal-Debloater-Alliance/universal-android-debloater-next-generation#240]
**Your phone model**: A53

**Packages documentation to update:**

```
com.samsung.android.svcagent
```

### Proposed description

> The APK has various icons in it + DiagMon library(telemetry), it has full access to internet, it occasionally runs a MainService for many consecutive hours.

**Comment by AnonymousWP** [comment]
Thanks. Next time, please create 1 issue for all Samsung packages.
