### ISSUE TITLE
Virustotal 

### ISSUE THREAD

**Issue by SFAZ38** [Universal-Debloater-Alliance/universal-android-debloater-next-generation#250]
Hello. Is this false positive? Because one of scanners found trojan in the executable.
![VirusTotal - File - b1d0e0fe625ed2def9eef3e77b32af2b24cd836ac2d60fa9cf2974a5879159c3 - Google Chrome 13 02 2024 00_08_51](https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation/assets/118468455/3e9e2ef0-3292-445d-bde1-c4364ca1a7e0)

**Comment by xe1st** [comment]
yes, false positive

**Comment by AnonymousWP** [comment]
Yes it is, likely because it pulls a file and/or the application isn't signed.

**Comment by xe1st** [comment]
bruh now windows defender does it as well
![avdetection](https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation/assets/140727743/685394cf-f89b-420f-8f97-fadfce6d2705)

**Comment by AnonymousWP** [comment]
Defender doesn't do anything here when I start it.

**Comment by xe1st** [comment]
> Defender doesn't do anything here when I start it.

maybe my defender configuration is diff or something?
cause it shows the uad exe 
![image](https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation/assets/140727743/dc06dc27-bf93-472d-9840-20afaf9cdf55)

**Comment by AnonymousWP** [comment]
Which version?

**Comment by xe1st** [comment]
> Which version?

uad v1 (last version)
windows 10 ltsc 21h2

**Comment by AnonymousWP** [comment]
I just updated my Defender and still nothing. Windows 11 though. But rest assured: code is reviewed by multiple users and I think it's because Defender thinks UAD-ng is downloading potential malware from an external source, while in fact it's trying to download the UAD-ng list.

**Comment by xe1st** [comment]
yeah ik the app itself isn't virus but let's hope defender detection isn't common. This still wouldn't be cool for the app.
