### ISSUE TITLE
"Error [TODO]" on restore

### ISSUE THREAD

**Issue by eleius** [Universal-Debloater-Alliance/universal-android-debloater-next-generation#265]
When I tried to restore my android tablet from a backup, UAD-NG showed "Error [TODO]".

The log shows lots of "internal errors" in sync.rs:131 like this:

`2024-02-17 14:23:43 ERROR [src/core/sync.rs:131] [RESTORE] pm uninstall com.oppo.engineermode.network -> Failure [DELETE_FAILED_INTERNAL_ERROR]`

**Comment by AnonymousWP** [comment]
Probably related and fixed to/in https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation/pull/261.
