### ISSUE TITLE
Linux installation sentence makes no sense

### ISSUE THREAD

**Issue by jxdv** [Universal-Debloater-Alliance/universal-android-debloater-next-generation#267]
The sentence from wiki about the linux installation: "with the by you used packaged manager"

![Screenshot from 2024-02-17 16-04-44](https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation/assets/138708600/1c4bfe32-45a6-4ea9-8f24-11cefbd4e39c)

**Comment by Frigyes06** [comment]
LOL what

**Comment by Frigyes06** [comment]
> I think what @Frigyes06 meant to say was, thank you @jxdv for reporting this, it's been fixed now.

Please don't speak in my name without my permission. I said what I said.

The issue, as indicated by the status of this issue, has been resolved.
Thanks for reporting @jxdv !
