### ISSUE TITLE
checking sha256 won't work automatically because of file path

### ISSUE THREAD

**Issue by jxdv** [Universal-Debloater-Alliance/universal-android-debloater-next-generation#270]
Most software which is shipped with checksums to verify that it hasn't been tampered with can be verified with these steps (on debian-based distros, but similar for different ones):
1. Download binary `imaginary-bin` and `imaginary-bin-sha256.txt`
2. sha256sum imaginary-bin
3. sha256sum --check imaginary-bin-sha256.txt

Which will result in `imaginary-bin: OK` if sums match, but won't work for uad-ng. 

1. sha256sum uad-ng-linux
2. sha256sum --check uad-ng-linux-checksum

Gives this output:
```
sha256sum: bin/uad-ng-linux: No such file or directory
bin/uad-ng-linux: FAILED open or read
sha256sum: WARNING: 1 listed file could not be read
```

Most likely because `uad-ng-linux-checksum` has following structure:

```
<hash> bin/uad-ng-linux
```

File paths don't match as we can see: `uad-ng-linux` != `bin/uad-ng-linux`. Of course It can still be verified, but it's annoying not being able to use the in-built method..

Fixing this is easy (just editing the CI). Feel free to assign me and I can do it in the upcoming days.

**Comment by Frigyes06** [comment]
It'd be appreciated if you could implement the fix

**Comment by jxdv** [comment]
> It'd be appreciated if you could implement the fix

Sure, I'll take a look in the upcoming days.
