### ISSUE TITLE
bug(uad-ng-list): 

### ISSUE THREAD

**Issue by timrosu** [Universal-Debloater-Alliance/universal-android-debloater-next-generation#272]
**Describe the bug**
When launching `uad-gui` (on arch linux), app says: "Downloading latest UAD-ng lists from GitHub. Please wait..." and doesn't finish. In terminal it writes a bunch of warnings and the most concerning is this part:
```
thread '<unnamed>' panicked at src/core/uad_lists.rs:197:60:
Unable to parse: Error("duplicate field `id`", line: 37496, column: 8)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Expected behavior**
List of apps to disable/uninstall.

**You have a solution?**
I looked at resources/assets/uad_lists.json and found that some entries have duplicated ids as error message shows.
Solution would be to remove those duplicated ids from entries.

**Logs**
[uad_lists.json](https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation/files/14324181/uad_lists.json)
[UAD_20240218.log](https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation/files/14324182/UAD_20240218.log)

**Comment by AnonymousWP** [comment]
Yup... We're aware. This slipped in with a PR and merge conflicts. I'll try to fix it.
