### ISSUE TITLE
bug(scope): UAD does not manage to get apps list and hide app list

### ISSUE THREAD

**Issue by Nojevah** [Universal-Debloater-Alliance/universal-android-debloater-next-generation#285]
**Describe the bug**
When opening UAD, it doesn't list apk and their status, instead it displays a message telling us to wait.
Clicking on "No internet?" does nothing.

![image](https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation/assets/7541249/79cde063-d433-4dcf-9530-8cba299e6802)

**Expected behavior**
Update of the list should be in background and only applied when user click on it.
Also the UAD should have an internal version in the app, for people who don't have Internet.

I know it's a temporary problem which should be fixed soon, but my bug report was to fix it for these cases of "no Internet connection".

**Comment by ThatGreenBlur** [comment]
I know its just a temporary problem but for people who really really need to use uadng rn i made a build thats stuck on old version use responsibly and update soon! https://github.com/ThatGreenBlur/uad-oldlistsystem/releases/tag/v1.0.0

**Comment by AnonymousWP** [comment]
> I know its just a temporary problem but for people who really really need to use uadng rn i made a build thats stuck on old version use responsibly and update soon! https://github.com/ThatGreenBlur/uad-oldlistsystem/releases/tag/v1.0.0

1.0.2 is already out: https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation/releases/tag/v1.0.2

**Comment by AnonymousWP** [comment]
Anyway, this issue has already been reported and is now fixed with 1.0.1. Download 1.0.2 manually.

**Comment by ThatGreenBlur** [comment]
> > I know its just a temporary problem but for people who really really need to use uadng rn i made a build thats stuck on old version use responsibly and update soon! https://github.com/ThatGreenBlur/uad-oldlistsystem/releases/tag/v1.0.0
> 
> 1.0.2 is already out: https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation/releases/tag/v1.0.2

i know and that was made when it was broken, ill take it down now to remove

**Comment by Nojevah** [comment]
Indeed, it works now. Thanks @ThatGreenBlur for the temporary build which helped me.
