### ISSUE TITLE
bug(app): unused variable 'res' when building no-self-update

### ISSUE THREAD

**Issue by Frigyes06** [Universal-Debloater-Alliance/universal-android-debloater-next-generation#308]
### Describe the bug

```
warning: unused variable: `res`
   --> src/gui/mod.rs:270:44
    |
270 |             Message::_NewReleaseDownloaded(res) => {
    |                                            ^^^ help: if this is intentional, prefix it with an underscore: `_res`
    |
    = note: `#[warn(unused_variables)]` on by default
```

### Expected behavior

There are no unused variables in the program

### You have a solution?

There are already parts that conditionally get excluded if building no-self-update. This code will need to be enclosed similarly too.

### Provide logs

N/a

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by edgy-b** [comment]
@Frigyes06 Any other features? `cargo build --features "no-self-update"`

Probably fixed, but can you test it? Builds fine for me before fix and after fix.

**Comment by edgy-b** [comment]
> @Frigyes06 Any other features? `cargo build --features "no-self-update"`
> 
> Probably fixed, but can you test it? Builds fine for me before fix and after fix.
> 
> https://github.com/edgy-b/universal-android-debloater-next-generation/tree/feat/no-self-update

nevermind, managed to reproduce, fixed

**Comment by edgy-b** [comment]
Nevermind, managed to reproduce, fixed.
