### ISSUE TITLE
bug(realme): possibility of some Realme options to disable / uninstall MIGHT brick some phone

### ISSUE THREAD

**Issue by Lolimipsu** [Universal-Debloater-Alliance/universal-android-debloater-next-generation#339]
### Describe the bug

While looking for some apps i find useless I can disable rather than uninstall i stumbled upon some options that are LIKELY very dangerous to disable
namely:
com.coloros.healthcheck
com.coloros.phonemanager
com.coloros.weather.service

see these links for references:
https://www.reddit.com/r/Realme/comments/12cgfbt/rui_40_debloat_list/
https://xdaforums.com/t/guide-eu-in-rom-realme-ui-debloat-list.4084795/

### Expected behavior

these options should not be available

### You have a solution?

remove or at least add the following to
![image](https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation/assets/44487404/bb74f903-1938-43c5-b2b5-4d025dffb4d9)

### Provide logs

NONE

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by AnonymousWP** [comment]
Thanks for filing an issue, but you filed the wrong template. It's clearly about packages, so why did you submit a bug regarding the application itself?

![image](https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation/assets/50231698/80f9fc14-90c1-4477-87a0-c8a2e524d0d9)

Closing this. Please file a new issue.
