### ISSUE TITLE
feat(android go): Debloat android go editions of General Mobile phones

### ISSUE THREAD

**Issue by erkinalp** [Universal-Debloater-Alliance/universal-android-debloater-next-generation#352]
### Describe the feature you want

Debloat android go editions of General Mobile phones. Android Go has gone unsupported, and Android go phones gets updated by regular Android apps; however, Android Go editions of apps are still not deleted from the phone.

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by AnonymousWP** [comment]
This is not an application feature request, but a package one. You can submit packages yourself, see https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation/issues/127.
