### ISSUE TITLE
pkg(com.zhiliaoapp.musically): TikTok pre-installed app 

### ISSUE THREAD

**Issue by vitoramaral10** [Universal-Debloater-Alliance/universal-android-debloater-next-generation#357]
### List your packages

- Package name: com.zhiliaoapp.musically
- List: OEM
- Removal: Recommended
- Description: This app is TikTok app.

### Acknowledgements

- [X] I removed all those packages on my phone. If not, why? Explain in the issue.
- [X] This issue is not a duplicate of an existing one.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by AnonymousWP** [comment]
Before you submit issues, please check whether the packages are there or not. It's already present in our list: https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation/blob/main/resources/assets/uad_lists.json#L14435
