### ISSUE TITLE
bug(scope): UAD stuck in downloading latest UAD-ing lists from GitHub

### ISSUE THREAD

**Issue by discomposed8890** [Universal-Debloater-Alliance/universal-android-debloater-next-generation#370]
### Describe the bug

Program stuck in "Downloading latest UAD-ng lists from GitHub. Please wait..." 

### Expected behavior

Downloading lists only took 1-2 seconds after opening the program

### You have a solution?

No solution found yet. Installing older version doesn't solve the issue either. Reinstalling UAD and restarting pc also yield no result.

### Provide logs

[UAD_20240323.log](https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation/files/14730401/UAD_20240323.log)

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by anime-shed** [comment]
Same here:
![image](https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation/assets/67512697/b6f10665-3371-43f8-a3ab-3f57233af818)

**Comment by anime-shed** [comment]
Is there an option to skip downloading and use the list that is already there??

**Comment by discomposed8890** [comment]
> Is there an option to skip downloading and use the list that is already there??



> Same here: ![image](https://private-user-images.githubusercontent.com/67512697/316221133-b6f10665-3371-43f8-a3ab-3f57233af818.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTExNzQxMDAsIm5iZiI6MTcxMTE3MzgwMCwicGF0aCI6Ii82NzUxMjY5Ny8zMTYyMjExMzMtYjZmMTA2NjUtMzM3MS00M2Y4LWEzYWItM2Y1NzIzM2FmODE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIzVDA2MDMyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJjMjFjZTUyYjFkYTU3ZGYzN2QyNjkzYTBjNTUzOGY2YWI1NjFlN2NkY2I2MzJiMmI5MjhkNzFhNTRhMzc1OTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CyFANZA4r6umSmiR0DtCi-SSs627v90ZTNpXoUT4zUc)

It worked for me yesterday and today it stopped working

**Comment by Knud3** [comment]
I was also coming to open issue about this. Its been down for about 11+ hours now.

I tried to delete everything about it from AppData and start with fresh "installation".

Starting app with settings and everything deleted:
```
2024-03-23 01:58:56 ERROR [src\core\config.rs:79] Failed to read config file: `The system cannot find the file specified. (os error 2)`
2024-03-23 01:58:56 ERROR [src\core\config.rs:81] Restoring default config file
2024-03-23 01:58:57 DEBUG [src\core\update.rs:174] Checking for UAD-ng update
2024-03-23 01:58:57 INFO  [src\gui\views\list.rs:136] -----------------------------------------------------------------
2024-03-23 01:58:57 INFO  [src\gui\views\list.rs:137] ANDROID_SDK: 34 | DEVICE: samsung SM-S928B
2024-03-23 01:58:57 INFO  [src\gui\views\list.rs:141] -----------------------------------------------------------------
```

After pressing "No internet?":
```
2024-03-23 03:17:02 INFO  [src\gui\views\list.rs:136] -----------------------------------------------------------------
2024-03-23 03:17:02 INFO  [src\gui\views\list.rs:137] ANDROID_SDK: 34 | DEVICE: samsung SM-S928B
2024-03-23 03:17:02 INFO  [src\gui\views\list.rs:141] -----------------------------------------------------------------
2024-03-23 03:17:02 WARN  [src\core\uad_lists.rs:208] Could not load remote debloat list
```

Even after that it got downloaded `uad_lists.json`, but got stuck to download screen.

**Comment by Knud3** [comment]
@AnonymousWP check this for line 35752 https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation/commit/c757f1a5067833a485d5de0dc5111dd60c5df5b4#diff-7b60c2b0f463a050d9284836dd992185ee8e09808f2b8432fccf85337e223ba0R35752

**Comment by Knud3** [comment]
So, workaround is to open `%userprofile%\AppData\Local\uad\uad_lists.json` and delete everything from line `35751` and before last `}`. After that press `No internet?`

**Comment by AnonymousWP** [comment]
Hi, apologies for this issue. I just published a statement regarding this: https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation/discussions/375.
