### ISSUE TITLE
pkg(com.qualcomm.qtil.btdsda): switching audio breaks output during phone calls

### ISSUE THREAD

**Issue by aryanpednekar45** [Universal-Debloater-Alliance/universal-android-debloater-next-generation#384]
### Describe the problem

Device: OnePlus 11
OS: OxygenOS 13.1

Can't switch audio output during phone calls
Audio comes from Earpiece regardless of the option selected (Speaker, Earpiece, Bluetooth) 

### You have a solution?

Reinstalling/Restoring app fixed the issue!
won't recommend this app being in recommended section

### Provide logs

Not needed ig

### Acknowledgements

- [X] This issue is not a duplicate of an existing one.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by AnonymousWP** [comment]
Good find! Glad I didn't disable it on my Nord 3. Submitted a PR.
