### ISSUE TITLE
bug(scope): com.vzw.apnlib description seems incorrect

### ISSUE THREAD

**Issue by VHSJayden** [Universal-Debloater-Alliance/universal-android-debloater-next-generation#386]
### Describe the bug

The com.vzw.obdm description seems incorrect. It seems like it is talking about Google Play telemetry module. 
![image](https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation/assets/90992730/b6e045cf-4f07-4af2-8573-01c36eafe1f5)

### Expected behavior

When phone connects, search for com.vzw.obdm and select it to see the description on the bottom of the window. I am assuming this only shows up if you have a verizon carrier.

### Provide logs

[UAD_20240326.log](https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation/files/14767384/UAD_20240326.log)

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by AnonymousWP** [comment]
Please use the proper template and re-open the issue. This is not a bug in UAD-ng itself.
