### ISSUE TITLE
com.vzw.hss.myverizon

### ISSUE THREAD

**Issue by minkyninja** [Universal-Debloater-Alliance/universal-android-debloater-next-generation#393]
### List your packages

Has a description carry-over from Call Filter, which it isn't. It's just My Verizon, the app. 

### Acknowledgements

- [X] This issue is not a duplicate of an existing one.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by AnonymousWP** [comment]
Are you sure? Why would people think it's a call filter?
