### ISSUE TITLE
Galaxy App fc, popup UI

### ISSUE THREAD

**Issue by oldman20** [Universal-Debloater-Alliance/universal-android-debloater-next-generation#398]
### Describe the problem

Android Q
Samsung N960F

Force Close Galaxy App after few seconds opened if debloat *com.google.android.overlay.gmsconfig*

popup UI revert similiar OASP UI if debloat *com.google.android.overlay.modules.permissioncontroller*

### You have a solution?

Not select 
*com.google.android.overlay.gmsconfig*
*com.google.android.overlay.modules.permissioncontroller*

 to debloat

### Provide logs

[UAD_20240327.log](https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation/files/14814550/UAD_20240327.log)

### Acknowledgements

- [X] This issue is not a duplicate of an existing one.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by aryanpednekar45** [comment]
I have them debloated on my S23 Ultra, doesn't seem to have this issue!
Old OneUI might be the issue!

**Comment by oldman20** [comment]
so that maybe, cause im still OneUI 2.5

**Comment by oldman20** [comment]
another issue on A10:
dont disable/ remove *framework-res__auto_generated_rro_vendor.apk* in `/vendor/overlay` folder, it will make headphone jack 3.5 not work

**Comment by AnonymousWP** [comment]
> popup UI revert similiar OASP UI if debloat com.google.android.overlay.modules.permissioncontroller

This description isn't clear to me. Be more specific please.

> another issue on A10: dont disable/ remove _framework-res__auto_generated_rro_vendor.apk_ in `/vendor/overlay` folder, it will make headphone jack 3.5 not work

Make a new issue for this.

**Comment by AnonymousWP** [comment]
@oldman20 Please follow-up on this.

**Comment by oldman20** [comment]
> @oldman20 Please follow-up on this.



> > popup UI revert similiar OASP UI if debloat com.google.android.overlay.modules.permissioncontroller
> 
> This description isn't clear to me. Be more specific please.
> 
> > another issue on A10: dont disable/ remove _framework-res__auto_generated_rro_vendor.apk_ in `/vendor/overlay` folder, it will make headphone jack 3.5 not work
> 
> Make a new issue for this.

Sorry im busy, add this too, pls

**Comment by oldman20** [comment]
> > popup UI revert similiar OASP UI if debloat com.google.android.overlay.modules.permissioncontroller
> 
> This description isn't clear to me. Be more specific please.

i mean when disble it, all popup ui will back to center screen appear instead bottom, and has The gray ui is very ugly like on aosp rom

**Comment by bornasalman** [comment]
Yes, it's an overlay. It's in the package name. All overlays are reskins of the AOSP versions. It doesn't affect anything but may cause more battery drain as the AOSP scale and colour scheme is less efficient than the overlay versions.

**Comment by AnonymousWP** [comment]
Thanks both of you, I'll fix that in the linked PR.
