### ISSUE TITLE
Why can't we copy description texts and open links?

### ISSUE THREAD

**Issue by TechFanTheo** [Universal-Debloater-Alliance/universal-android-debloater-next-generation#400]
### Describe the feature you want

We can't copy the packages description and can't open the sources links. Now I now your average Githuber will just consult the UAD lists, but th average user is going to be frustrated. Not sure if this a bug or a lacking feature.

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by AnonymousWP** [comment]
Apparently you just checked the checkbox to get rid of everything? The issue already exists: https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation/issues/49.
