### ISSUE TITLE
Huawei HarmonyOS 4 debloat report

### ISSUE THREAD

**Issue by domy86** [Universal-Debloater-Alliance/universal-android-debloater-next-generation#410]
### Describe the problem

I have recently upgraded Huawei Mate 20 X to HarmonyOS 4 and Huawei Mate 10 to EMUI 12. Below are my 2 cents on removed packages and behavior afterwards.

### You have a solution?

**com.huawei.android.hwaps:**
To declutter settings app after removal, follow this procedure: select some resolution > uninstall package > restart phone > restore package > click on resolution in settings, it will disappear > uninstall package > restart phone

**com.huawei.android.thememanager:**
A ringtone cannot be changed if you remove this package, not only notification sound.

**com.huawei.arengine.service:**
Needed for nice tool AR Measure, but you may disable it and AR Measure will still work.

**com.huawei.coauthservice:**
Needed for manual apk installation.

**com.huawei.controlcenter:**
Needed for Super Device or Device+, safe to remove if you don't use this, it will also declutter action center.

**com.huawei.featurelayer.sharedfeature.map:**
Used to show maps inside Calendar and Gallery, they will complain if you uninstall it, disable instead.

**com.huawei.harmonyos.foundation:**
Settings app and APK installation will become slow if you uninstall this.

**com.huawei.hwddmp:**
Not only breaks the dialer app, but causes lag in whole system too.

**com.huawei.hwstartupguide:**
Cannot uninstall, only disable.

**com.huawei.nearby:**
Needed to show a preview of recently opened apps in task manager. I agree, makes no sense, but that what it is.

**com.huawei.pcassistant:**
Cannot uninstall, only disable.

**com.huawei.security.privacycenter:**
Needed for Permission Manager to open.

**com.huawei.securitymgr:**
This is the password vault or password manager too.

**com.huawei.securityserver:**
Needed for face unlock, black screen will be shown if you remove this package.

**com.huawei.systemmanager:**
This is more that a phone cleaner, you will lose a lot of settings like battery and notifications management if you remove this.

**com.huawei.systemserver:**
Needed for navigation with a fingerprint reader that is on Mate 10, but fingerprint unlock will still work if you remove it.

**com.huawei.ohos.*:**
These ohos packages are related to service widgets with belonging names. For example, if you uninstall com.huawei.ohos.camera, service widget Camera will disappear, Camera app will still work without issues. If you either don't use any of Huawei apps or don't need such widgets, you may remove all ohos packages. Disabling them will not remove widgets.

**Special and kinda important thing:**

If you remove **com.huawei.iaware** and/or **com.huawei.powergenie**, system will start lagging a little bit (you will notice it while scrolling and on some animations, for example scrolling installed apps), battery consumption will become slightly higher and battery stats will disappear soon. At the same time, logcat will be full of errors like: `PowerKit: PG Server is not found. calling pid xxxx`.

OK, this is cons but someone will benefit from removing those two packages or at least com.huawei.powergenie, including me. No matter what I did, I couldn't make Microsoft Teams notifications to work in timely manner while screen is off, and only Microsoft Teams notifications. I use the same settings for all other messaging apps and all these apps are working without any issues. OK, there is some slight delay but acceptable. Once I either press the power button or scan my fingerprint, all Teams notifications will show up immediately.

So, if Microsoft Teams is important for you, uninstall com.huawei.powergenie. Disabling will not work as it will be enabled after phone restart.

### Provide logs

-

### Acknowledgements

- [X] This issue is not a duplicate of an existing one.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by AnonymousWP** [comment]
Thanks for the extensive issue, but it seems like you used the wrong template. Please use the correct one, because now information is missing.
