### ISSUE TITLE
pkg: duplicate packages in uad_list

### ISSUE THREAD

**Issue by jxdv** [Universal-Debloater-Alliance/universal-android-debloater-next-generation#429]
### Describe the bug

Not really a bug, but I noticed that there are duplicate packages present in the debloat list.

For example ```com.samsung.android.incall.contentprovider``` is present twice:

```json
  "com.samsung.android.photoremasterservice": {
    "list": "Oem",
    "description": "PhotoRemasterService\nIf removed, Photo Remaster in the gallery won't work.",
    "dependencies": [],
    "neededBy": [],
    "labels": [],
    "removal": "Advanced"
  },
...
  "com.samsung.android.photoremasterservice": {
    "list": "Oem",
    "description": "Photo remaster will not work after remove, if this feature exist, still unknown.",
    "dependencies": [],
    "neededBy": [],
    "labels": [],
    "removal": "Advanced"
  },
```

The full list of duplicate packages according to my IDE:

```
com.samsung.attribution
com.samsung.android.photoremasterservice
com.samsung.android.widget.pictureframe
com.samsung.android.sm_cn
com.samsung.android.incall.contentprovider
com.samsung.android.wifi.softap.resources
com.samsung.sait.sohservice
com.samsung.android.secsoundpicker
com.samsung.android.singletake.service
com.samsung.ims.smk
com.samsung.internal.systemui.navbar.gestural_no_hint
com.samsung.internal.systemui.navbar.sec_gestural
com.samsung.internal.systemui.navbar.sec_gestural_no_hint
com.samsung.android.wallpaper.res
```

### Expected behavior

Do not have duplicate packages in the debloat list.

### You have a solution?

Remove the duplicate packages.

### Provide logs

N/A

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by AnonymousWP** [comment]
Thanks for this. Arguably this should have been part of https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation/issues/new?assignees=&labels=package%3A%3Adocumentation&projects=&template=5-update-apps-description-or-recommendation.yml&title=pkg%28scope%29%3A+ actually, but I'll leave it like this.
