### ISSUE TITLE
bug(scope): Startup on crash

### ISSUE THREAD

**Issue by EnderNon** [Universal-Debloater-Alliance/universal-android-debloater-next-generation#438]
### Describe the bug

Ran the program in linux, I get an error in terminal.

### Expected behavior

the app to run

### Provide logs

[UAD_20240430.log](https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation/files/15170062/UAD_20240430.log)

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by EnderNon** [comment]
oh right also, I'm running ArchLinux with KDE Plasma, on Linux Zen kernel

**Comment by edgy-b** [comment]
> > oh right also, I'm running ArchLinux with KDE Plasma, on Linux Zen kernel
> 
> @EnderNon Duplicate #383
