### ISSUE TITLE
pkg(scope): com.google.android.rkpdapp or com.android.remoteprovisioner

### ISSUE THREAD

**Issue by aryanpednekar45** [Universal-Debloater-Alliance/universal-android-debloater-next-generation#450]
### List your packages

- Package name: RemoteProvisioner
- List: Google/AOSP
- Removal: Expert
- Description: RemoteProvisioner is likely related to new Google Passkeys "Passwordless login" feature
After uninstalling, no issues occurred

### Acknowledgements

- [X] I removed all those packages on my phone. If not, why? Explain in the issue.
- [X] This issue is not a duplicate of an existing one.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by AnonymousWP** [comment]
> I reopen this because I don't see this packages in the list after almost a year. Also I would add some more accurate (I think) info to description: Description: "Checks integrity of device root and updates certificates. Usually bank apps depend on it. \nUpdates once a day ( https://cs.android.com/android/platform/superproject/main/+/main:packages/modules/RemoteKeyProvisioning/app/src/com/android/rkpdapp/BootReceiver.java;drc=71f31db55f56a2d7b183f1032e391152ecbb78db;l=55 ). \nhttps://source.android.com/docs/core/ota/modular-system/remote-key-provisioning \nI don't mess with this package."
> 
> Edit: I thought that reopens automagically when comment, hope this is enough to have a review of the issue.

You should see it now, the description can be changed. Could you please open a PR yourself?
