### ISSUE TITLE
pkg(scope): com.oplus.nas (Network Services)

### ISSUE THREAD

**Issue by aryanpednekar45** [Universal-Debloater-Alliance/universal-android-debloater-next-generation#451]
### List your packages

- Package name: Network Services (com.oplus.nas)
- List: OEM
- Removal: Recommended/Advanced
- Description: Has Location & Phone permission, can read your Call logs. Runs in background
After Disabling, no issues occured (OxygenOS 14, OnePlus 11)

### Acknowledgements

- [X] I removed all those packages on my phone. If not, why? Explain in the issue.
- [X] This issue is not a duplicate of an existing one.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by Blitz517** [comment]
about de-bloater f-droid I mention it, because its easy to recover back apps using twrp

**Comment by AnonymousWP** [comment]
Why would it be `Advanced`? What is its purpose? 👀
