### ISSUE TITLE
docs(scope): add run-specific instructions to README or Wiki

### ISSUE THREAD

**Issue by ticklemyIP** [Universal-Debloater-Alliance/universal-android-debloater-next-generation#460]
### Describe the documentation you want to change

The compiled binary in Releases does not come with the run permission enabled by default for Linux builds, I don't know about the other OS versions. This may confuse beginners or people who are used to the legacy UAD packages which run by default. This is not strictly specific to beginners though as I myself had to troubleshoot this, even though I know my way around Linux a bit better.

I recommend specifying that users on Linux (and possibly other OS') either need to check the run persmission toggle in their file properties (depending on DE) or they need to run a `chmod` command through the terminal. This could be specified either in the README or the Wiki. ~~I will make a PR to the README with this addition.~~ Noticed that there are instructions in the [Getting started](https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation/wiki/Getting-started) section, but I can't contribute unfortunately. The Linux dropdown should be extended with the above suggestion, but for clarity I would like it better if the fundamental instructions such as Getting started would be placed in the README. If the devs would like, I volunteer to contribute and expand it.

### Acknowledgements

- [X] This issue is not a duplicate of an existing documentation change request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by AnonymousWP** [comment]
Fixed in https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation/wiki/Getting-started/_history.
