### ISSUE TITLE
pkg(scope): me.phh.treble.app

### ISSUE THREAD

**Issue by Byteintosh** [Universal-Debloater-Alliance/universal-android-debloater-next-generation#468]
### List your packages

- Package name: PhhTrebleApp `me.phh.treble.app`
- List: Oem
- Removal: Unsafe
- Description: Used for settings GSI rom that based by Phh Treble. This should not be remove.

### Acknowledgements

- [X] I removed all those packages on my phone. If not, why? Explain in the issue.
- [X] This issue is not a duplicate of an existing one.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by Blitz517** [comment]
we want really custom rom to be listed?

**Comment by AnonymousWP** [comment]
Hmm, we could. We could assign it to the `Oem` list. I believe there are already some packages there.
