### ISSUE TITLE
pkg(scope): Removing com.huawei.android.internal.app breaks the share function in many applications

### ISSUE THREAD

**Issue by Artem13327** [Universal-Debloater-Alliance/universal-android-debloater-next-generation#485]
Honor 7A Pro, EMUI 8.0.0, Android 8.0.0
However, what’s interesting is that the share function works in some applications

### Acknowledgements

- [X] This issue is not a duplicate of an existing one.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by AnonymousWP** [comment]
Why didn't you use the template? It's there for a reason. Closing this until you're using the template.
