### ISSUE TITLE
feat(scope): Copy package name

### ISSUE THREAD

**Issue by Artem13327** [Universal-Debloater-Alliance/universal-android-debloater-next-generation#488]
### Describe the feature you want

Sometimes you need to copy the package name, for example for searching or posting here

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by AnonymousWP** [comment]
This isn't possible easily, see https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation/issues/49. Closing as it's a duplicate issue.
