### ISSUE TITLE
pkg(scope): miui.systemui.plugin

### ISSUE THREAD

**Issue by spaceXrace** [Universal-Debloater-Alliance/universal-android-debloater-next-generation#491]
### List your packages

- Package name: miui.systemui.plugin
- Current list: OEM
  - Proposed list: OEM
- Current removal: Advanced
  - Proposed removal: Advanced
- Current description: System UI Plug-in. When removed, Android will use the AOSP style volume bar.
  - Proposed description: System UI Plug-in. When removed, Android will use the AOSP style volume bar and reboot menu. Will break the iOS-style quick settings.

### Acknowledgements

- [X] This issue is not a duplicate of an existing one.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by Blitz517** [comment]
what do you mean by reboot menu?

**Comment by spaceXrace** [comment]
The menu that appears when you hold the power button, which gives you the option to turn off the device or reboot it. Maybe reboot menu wasn't the best description, sorry!

-------- Original Message --------

**Comment by Blitz517** [comment]
its only on hyperos or beta miui? on my phone i only lose miui style volume bar

**Comment by spaceXrace** [comment]
Interesting. I'm on HyperOS, I loose all the things mentioned.

Sent from Proton Mail Android

-------- Original Message --------

**Comment by nyveZz** [comment]
Can confirm on HyperOS. It also breaks the control center and reboot options for me.

**Comment by spaceXrace** [comment]
Are your reboot options broken or just back to AOSP? Mine are AOSP, but I am on the chinese version

-------- Original Message --------

**Comment by AnonymousWP** [comment]
I reflected this conversation in the linked PR.

**Comment by cameronj86** [comment]
Nitpicky, and yes I should've read the entire description before uninstalling instead of just skimming, but since losing system Quick Settings will have a larger impact to the average user than gaining AOSP volume setting, perhaps it can be listed first? I can do the PR myself if desired.

**Comment by AnonymousWP** [comment]
> Nitpicky, and yes I should've read the entire description before uninstalling instead of just skimming, but since losing system Quick Settings will have a larger impact to the average user than gaining AOSP volume setting, perhaps it can be listed first? I can do the PR myself if desired.

Yes please open a PR and I'll have a look at it.
