### ISSUE TITLE
bug(compilation): Ambiguous name error when compiling from source

### ISSUE THREAD

**Issue by Minoxs** [Universal-Debloater-Alliance/universal-android-debloater-next-generation#501]
### Describe the bug

When compiling from source (with or without --release) an error is raised about ambiguous naming in the iced_style package.

![image](https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation/assets/53454542/b77f2c7b-b8fe-43f8-8be5-bcfb4e84838f)

The next one might also happen:

![image](https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation/assets/53454542/b13b24c3-3295-4771-8c28-93e05e7b8cd3)

### Expected behavior

UAD compiles without error.

### You have a solution?

Perhaps not the correct solution, but as a temporary workaround:

Look for the files which raised errors and change the following:

![image](https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation/assets/53454542/319291bc-3dad-46af-905c-c09739b259fc)

![image](https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation/assets/53454542/c58fcf72-6404-411a-926f-71ea8fa463b1)

### Provide logs

N/A

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by B0ney** [comment]
Does `rustup update` solve the issue?

**Comment by Minoxs** [comment]
I just tried it and it did not solve. Same issue.

I even cleared `.cargo\registry` after updating and still nothing.

**Comment by Frigyes06** [comment]
Is this still an issue?

**Comment by Minoxs** [comment]
Yep, still happening:

![image](https://github.com/user-attachments/assets/5425f2f0-d50e-4250-a113-6c4d7ee1da18)

![image](https://github.com/user-attachments/assets/35541f96-9184-4a03-acd0-c9f8bae3a0cb)

Cargo freshly updated. Windows 64 bits.

**Comment by AnonymousWP** [comment]
> Yep, still happening:
> 
> ![image](https://private-user-images.githubusercontent.com/53454542/393067267-5425f2f0-d50e-4250-a113-6c4d7ee1da18.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQxODI1NDIsIm5iZiI6MTczNDE4MjI0MiwicGF0aCI6Ii81MzQ1NDU0Mi8zOTMwNjcyNjctNTQyNWYyZjAtZDUwZS00MjUwLWExMTMtNmM0ZDdlZTFkYTE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE0VDEzMTcyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFmNTUzMGM1MTNjZGI1NDdmZTQ4Y2MyNWE2MmIxMTUwNmFlOTBmMGUxZWYwZmQxZTI0NDhjZmU0Yzk3NzYzM2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.NOARkP9HyghJui_4j3nUAopXfHqxqCxpCEBDDJlfnu4)
> 
> ![image](https://private-user-images.githubusercontent.com/53454542/393067331-35541f96-9184-4a03-acd0-c9f8bae3a0cb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQxODI1NDIsIm5iZiI6MTczNDE4MjI0MiwicGF0aCI6Ii81MzQ1NDU0Mi8zOTMwNjczMzEtMzU1NDFmOTYtOTE4NC00YTAzLWFjZDAtYzlmOGJhZTNhMGNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE0VDEzMTcyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ5MTY4ZTFkZDQzMTdiNzQ1NGI5NmM2MDdlMGJiNmFhMWE1YjU4MGY4MDQ4MjQ4ZWZkNmY2OWIzMGI4M2Y5OGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0._3I0PwEVMtLIvIEkTjV7_Y3QXMSUyLEtSMAM6z_lA3s)
> 
> Cargo freshly updated. Windows 64 bits.

Would you be able to fix this and open a PR? Would be nice.

**Comment by Minoxs** [comment]
I can definitely try! I opened an issue here because I'm unsure if this only happens to me or if it happens to others as well. It would be nice if someone else could try and confirm if this happens on another machine as well.

**Comment by Minoxs** [comment]
I fiddled with this for a bit and realised I had the wrong toolchain active (version 1.70). After going to stable and updating to 1.83 it compiles just fine.

My bad!!
