### ISSUE TITLE
bug(scope): no devices/emulators found

### ISSUE THREAD

**Issue by vitormarchini** [Universal-Debloater-Alliance/universal-android-debloater-next-generation#509]
### Describe the bug

I've been able to use the UAD other times normally. Today I tried to use it normally, but it doesn't identify my device in any way, even though I leave USB debugging active. What happens?

### Expected behavior

I want my device to be recognized again so I can delete the app I want.

### Provide logs

![image](https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation/assets/53418150/6eb2fc49-1f00-4ac4-9c3a-27bc5b70b6d5)

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by AnonymousWP** [comment]
Please [post logs](https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation/wiki/FAQ#where-are-the-logfiles).

**Comment by edgy-b** [comment]
@vitormarchini 
Go to Developer and try 
 - revoking USB connections
 - turn on/off USB debugging

**Comment by AnonymousWP** [comment]
Closing this as we gave a solution for the problem, and also because we didn't get any reply.
