### ISSUE TITLE
`pkg(com.google.android.gms)`: Sync broken, Gmail cannot detect G account

### ISSUE THREAD

**Issue by Rudxain** [Universal-Debloater-Alliance/universal-android-debloater-next-generation#517]
### Describe the problem

After uninstalling and reinstaling G Play Services & G Services Framework (`com.google.android.gsf`), the "Contacts" option in Google account sync disappeared, and "Google One" no longer backs-up contacts, forcing me to do it manually with vCard files.

After reinstalling (and updating) `com.google.android.gm` (Gmail, not Play Services), it no longer detects **any** Google account, even if it shows up in the system's account list and it was added post-GMS-reinstall.

I opened this issue because this should be documented, not because I believe UAD is wrong. I knew very well that uninstalling GMS would break stuff, but I reinstalled it because it broke too much stuff and [microG](https://github.com/microg/GmsCore) requires unlocked bootloader.

- Android: 12.0
- Model: SM-A315G

### You have a solution?

I've tried:
- clearing GMS data
- removing and re-adding my account
- rebooting after doing either of above

Unfortunately, the only known reliable solution is a factory reset

### Provide logs

`None`

### Acknowledgements

- [X] This issue is not a duplicate of an existing one.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by Rudxain** [comment]
Setup Wizard is uninstalled, I'm suspecting that's why Accounts don't work properly

**Comment by Rudxain** [comment]
Gmail now detects account after enabling SetupWizard!

Still can't sync Contacts. Guess, I'll have to factory-reset

**Comment by AnonymousWP** [comment]
Good to know, thanks for confirming.

**Comment by AnonymousWP** [comment]
@Rudxain Quick question. So do you want me to add this to the description of which package? There are many packages with ` SetupWizard` in the name.

**Comment by Rudxain** [comment]
`com.google.android.setupwizard`. It makes sense considering the "mobile identity management"

**Comment by Rudxain** [comment]
Should I change the title? The real culprit was SW, not GMS. But I still don't know what happened to Calendar and Contacts

**Comment by Rudxain** [comment]
The Calendar magically works again! It seems Google has updated Play Services this week, Now S Calendar properly fetches all the events from all my accounts!

Contact-sync seems to have been working for a longer time, but IDK why. Maybe I did something?
