### ISSUE TITLE
pkg(scope): com.coloros.colordirectservice (Change description)

### ISSUE THREAD

**Issue by aryanpednekar45** [Universal-Debloater-Alliance/universal-android-debloater-next-generation#546]
### List your packages

- Package name: Screen Recognition
- Current list: OEM
- Proposed list: OEM
- Current removal: Recommended
- Proposed removal: Recommended
- Current description: Boo awareness screen
Smart things, also have something to Breeno touch
- Proposed description: Screen Recognition (Breeno Touch)
This app is used to recognize screen contents and provide quick access to relevant services (like Text Extraction, AI Summarizer)
(com.coloros.ocrscanner, com.coloros.ocrservice, com.oplus.ocs, com.oplus.aiunit, com.coloros.ocs.opencapabilityservice are also needed for this to work)

### Acknowledgements

- [X] This issue is not a duplicate of an existing one.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by AnonymousWP** [comment]
I'm making it `Advanced`.

**Comment by aryanpednekar45** [comment]
> I'm making it `Advanced`.

Recommended would be better. Uninstalling it doesn't have any issues.

**Comment by AnonymousWP** [comment]
The Wiki is leading here: https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation/wiki/FAQ

> Recommended -- Pointless or outright negative packages, and/or apps available through Google Play.
> Advanced -- Breaks obscure or minor parts of functionality, or apps that aren't easily enabled/installed through Settings/Google Play. This category is also used for apps that are useful (default keyboard/gallery/launcher/music app.) but that can easily be replaced by a better alternative.

**Comment by aryanpednekar45** [comment]
> The Wiki is leading here: https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation/wiki/FAQ
> 
> > Recommended -- Pointless or outright negative packages, and/or apps available through Google Play.
> 
> > Advanced -- Breaks obscure or minor parts of functionality, or apps that aren't easily enabled/installed through Settings/Google Play. This category is also used for apps that are useful (default keyboard/gallery/launcher/music app.) but that can easily be replaced by a better alternative.

Recommended. It's not a useful app and uninstall it doesn't do any harm

**Comment by aryanpednekar45** [comment]
> I'm making it `Advanced`.

Ok 👍🏻
