### ISSUE TITLE
bug(theme): `Auto` partially updates views, when changing DE color-scheme

### ISSUE THREAD

**Issue by Rudxain** [Universal-Debloater-Alliance/universal-android-debloater-next-generation#550]
### Describe the bug

https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation/pull/531#issuecomment-2220897348

https://discord.com/channels/1168607797081022514/1171387180409692160/1260638729463402638 :
> The background doesn't update if the system theme changes while the program is running
> But the widgets do

New repro:
1. Go to Settings
2. Ensure Auto theme is set
3. Change desktop environment theme
4. ~~Click any empty space in the Settings View~~ Focus the window

### Expected behavior

Either:
- view shouldn't update colors until switching back-&-forth between views
- full view gets an updated palette

### Provide logs

There's nothing. Only "change setting" events, which only get logged if user changes UAD theme, not DE theme

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by Frigyes06** [comment]
Can reproduce on Arch linux

**Comment by AnonymousWP** [comment]
@Universal-Debloater-Alliance/developers Can we fix this so we can release 1.1.0?

**Comment by Rudxain** [comment]
I might attempt to fix it, but I have to read the Iced docs first

**Comment by AnonymousWP** [comment]
Removed this from the v1.1.0 release milestone as it's likely something we can't fix.

**Comment by lavafroth** [comment]
The theme will change if you restart the program. Sadly, this is more of an iced-rs issue.
