### ISSUE TITLE
bug(exec): can't open window

### ISSUE THREAD

**Issue by Rudxain** [Universal-Debloater-Alliance/universal-android-debloater-next-generation#556]
### Describe the bug

UAD opens the window briefly, then it closes itself. Possibly a crash/panic.

This was originally reported by 2 users on the Discord guild. I haven't tested it myself (yet)

Running on an NVIDIA system with drivers from 2017

### Expected behavior

It must open (obviously)

### You have a solution?

> [I suspect Microsoft or NVIDIA pushed an update that broke UAD](https://discord.com/channels/1168607797081022514/1168607798196715573/1262273395316232253)

### Operating System

Windows

### Provide logs

_None 💀_

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by Alpha-Radke** [comment]
Yes I can confirm this is 99% because of older GPU drivers that I started using for my GTX 1080 on fresh Windows 10 (22H2 19045.3448)
NVIDIA Driver 385.69
No iGPU Intel i3-10105F
[UAD_20240712.log](https://github.com/user-attachments/files/16233341/UAD_20240712.log)

**Comment by Frigyes06** [comment]
Cannot repro on Win 10 and an AMD video card

**Comment by AnonymousWP** [comment]
If it's related to GPU drivers, then is it even something we can fix?

**Comment by Rudxain** [comment]
> something we can fix?

I doubt it. Even if it was a problem in the program, it would most likely be related to `wgpu`.

Maybe the bug has been fixed since dependencies were updated?

Anyways, I'm closing this because of lack of info
