### ISSUE TITLE
pkg(scope): com.samsung.adnroid.knox.app.networkfilter uninstalling crashes Bluetooth

### ISSUE THREAD

**Issue by Tirgatt** [Universal-Debloater-Alliance/universal-android-debloater-next-generation#558]
### Describe the problem

After uninstalling com.samsung.android.knox.app.networkfilter, Bluetooth on my Samsung Galaxy Z Flip 6 keeps crashing with the message 'Bluetooth keeps stopping'.

Device Specifications (as shipped):
One UI Version: 6.1.1
Android Version: 14
Security Patch Level: June 1, 2024
Baseband Version: F741BXXU1AXFD

Additional Information:
I purchased the device directly from the Samsung Shop App.
The package did not come directly from Samsung; the label read "Kuehne & Nagel (AG & Co.) KG".

### You have a solution?

If I restore com.samsung.android.knox.app.networkfilter, Bluetooth works fine again.

### Provide logs

[UAD_20240719.log](https://github.com/user-attachments/files/16316440/UAD_20240719.log)

### Acknowledgements

- [X] This issue is not a duplicate of an existing one.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by Tirgatt** [comment]
I forgot to say that I used the "Recommended" filter when I uninstalled com.samsung.android.knox.app.networkfilter. I did not expect a package marked as "Recommended" to cause essential functions like Bluetooth to stop working.

**Comment by king-gheedorah** [comment]
Experienced the same issue and solution.

**Comment by AnonymousWP** [comment]
Thanks for telling us. I'll fix this.

**Comment by king-gheedorah** [comment]
Looks good, thanks!

Sep 18, 2024 6:31:46 a.m. Anonymoussaurus ***@***.***>:
