### ISSUE TITLE
Recommended apps breaks System Navigation

### ISSUE THREAD

**Issue by akarn911** [Universal-Debloater-Alliance/universal-android-debloater-next-generation#571]
### Describe the problem

These five recommended apps breaks the system navigation when switching between 3-button and gestures.
( I am using Motorola phone - Moto E13 )
1. com.google.android.overlay.gmsconfig.comms
2. com.google.android.overlay.gmsconfig.geotz
3. com.google.android.overlay.gmsconfig.personalsafety
4. com.google.android.overlay.modules.modulemetadata.forframework
5. com.google.android.overlay.modules.permissioncontroller.forframework

### You have a solution?

Remove them from recommended list.

### Acknowledgements

- [X] This issue is not a duplicate of an existing one.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by schbrns** [comment]
I mean, you shouldn't be removing overlay modules. Are these not set to expert?

**Comment by akarn911** [comment]
These are in recommended list.

**Comment by AnonymousWP** [comment]
You don't need to close your issue:

> [AnonymousWP](https://github.com/AnonymousWP) linked a pull request [33 minutes ago](https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation/issues/571#event-14527466009) that will close this issue

**Comment by akarn911** [comment]
Ok.
Thank you 👍
