### ISSUE TITLE
com.casper.turkiye seems to be just aosp crap

### ISSUE THREAD

**Issue by Twig6943** [Universal-Debloater-Alliance/universal-android-debloater-next-generation#572]
### List your packages

- Package name: com.casper.turkiye
- List: OEM
- Removal: Recommended
- Description: https://play.google.com/store/apps/details?id=com.casper.turkiye&hl=en

### Acknowledgements

- [X] I removed all those packages on my phone. If not, why? Explain in the issue.
- [X] This issue is not a duplicate of an existing one.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by lavafroth** [comment]
Nope, this package is not in AOSP. It should be added to some other list (OEM perhaps?)
