### ISSUE TITLE
bug(scope): Can't uninstall select t-mobile selections

### ISSUE THREAD

**Issue by whoisleigh** [Universal-Debloater-Alliance/universal-android-debloater-next-generation#579]
### Describe the bug

![image](https://github.com/user-attachments/assets/a9466053-efcd-4af2-85dc-0e88bc0e7472)
When I try to uninstall these nothing happens

### Expected behavior

I expected them to be removed like the other bloatware.

### You have a solution?

No i need a solution

### Operating System

Windows

### Window Manager

OS

### Desktop Environment

OS

### Provide logs

i

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by AnonymousWP** [comment]
Try disabling instead of uninstalling, see https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation/wiki/FAQ#how-is-it-possible-to-delete-a-system-package-without-root-permission. The apps are probably mounted on `/system`.
