### ISSUE TITLE
pkg(scope): Recommended debloat issue on OPPO

### ISSUE THREAD

**Issue by Aetumn12** [Universal-Debloater-Alliance/universal-android-debloater-next-generation#585]
### Describe the problem

So i have an OPPO phone and i debloated all the apps in the recommended list only.The phone boots up fine until im brought upto the home screen and then the screen started flashing and phone becomes unresponsive

### You have a solution?

undo the debloat by performing factory reset

### Provide logs

[UAD_20240817.log](https://github.com/user-attachments/files/16639383/UAD_20240817.log)

### Acknowledgements

- [X] This issue is not a duplicate of an existing one.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by AnonymousWP** [comment]
Do you have an idea which package is responsible for this?

**Comment by Asra05** [comment]
> Do you have an idea which package is responsible for this?

The package causing this problem on my device seems to be “com.coloros.weather.service”

**Comment by AnonymousWP** [comment]
Uh-oh, that one is also present on my OnePlus Nord 3. I'll work on this.

**Comment by AnonymousWP** [comment]
I have this disabled on my Nord 3 and 13R and without any problems. I also know some other people that have this disabled without any issues. Did you disable or uninstall by the way, @Aetumn12 @Asra05?

**Comment by rafnov** [comment]
> I have this disabled on my Nord 3 and 13R and without any problems. I also know some other people that have this disabled without any issues. Did you disable or uninstall by the way, [@Aetumn12](https://github.com/Aetumn12) [@Asra05](https://github.com/Asra05)?

I've disabled that on two Realme devices (GT Neo 2, 7 Pro) and nothing bad happened as far. I'm wondering if it's worthy to keep the package marked as unsafe if we have only two confirmed cases of causing problems.

**Comment by slvlng** [comment]
> I have this disabled on my Nord 3 and 13R and without any problems. I also know some other people that have this disabled without any issues.

When I uninstalled these packages on Moto (Android 11), I was not even able to open the Settings until I reinstalled them.

>com.android.theme.color.black
com.android.theme.color.cinnamon com.android.theme.color.green com.android.theme.color.ocean com.android.theme.color.orchid com.android.theme.color.purple com.android.theme.color.space
com.android.theme.icon.pebble com.android.theme.icon.taperedrect com.android.theme.icon.vessel com.android.theme.icon_pack.rounded.systemui com.android.theme.icon_pack.rounded.themepicker

**Comment by AnonymousWP** [comment]
> > I have this disabled on my Nord 3 and 13R and without any problems. I also know some other people that have this disabled without any issues.
> 
> When I uninstalled these packages on Moto (Android 11), I was not even able to open the Settings until I reinstalled them.
> 
> > com.android.theme.color.black
> > com.android.theme.color.cinnamon com.android.theme.color.green com.android.theme.color.ocean com.android.theme.color.orchid com.android.theme.color.purple com.android.theme.color.space
> > com.android.theme.icon.pebble com.android.theme.icon.taperedrect com.android.theme.icon.vessel com.android.theme.icon_pack.rounded.systemui com.android.theme.icon_pack.rounded.themepicker

That's not related to this package at all.

**Comment by slvlng** [comment]
> That's not related to this package at all.

?

All these packages from the OP's log.

I also meant that com.coloros.weather.service might not be related to the OP's issue at all...
