### ISSUE TITLE
pkg(Motorola): Multiple apps missing for Motorola Edge (2024)

### ISSUE THREAD

**Issue by Lost-Entrepreneur439** [Universal-Debloater-Alliance/universal-android-debloater-next-generation#594]
### List your packages

APP 1:
- Package name: com.android.internal.systemui.navbar.hidegestural
- List: AOSP
- Removal: Expert
- Description: This package handles the internal management of gesture-based navigation bars in the Android system UI. Removing it may disrupt the functionality of gesture navigation, which is integral to the user interface.

APP 2:
- Package name: com.android.internal.systemui.navbar.transparent
- List: AOSP
- Removal: Advanced
- Description:This package is responsible for managing the transparency of the navigation bar in the Android system UI. It controls how the navigation bar appears in terms of opacity, allowing it to blend with the background or be more visible. Removing this package may affect the visual appearance of the navigation bar, potentially leading to a less customizable or aesthetically inconsistent UI.

APP 3:
- Package name: com.android.phone.overlay.motcommon
- List: OEM
- Removal: Advanced
- Description: This package is part of Motorola's custom overlay for phone-related features and UI elements. It is likely involved in providing specific functionality or visual customization for phone operations on Motorola devices. Removing this package could affect certain phone features or the look and feel of phone-related settings specific to Motorola devices.

APP 4:
- Package name: com.android.systemui.accessibility.accessibilitymenu.auto_generated_rro_product__
- List: AOSP
- Removal: Advanced
- Description: This package is associated with the Accessibility Menu in Android's system UI, specifically related to auto-generated resources for the menu. It helps manage accessibility features that assist users with disabilities. Removing this package might disable or alter accessibility options provided through the Accessibility Menu, potentially affecting users who rely on these features.

APP 5:
- Package name: com.android.wifi.resources.overlay.motCommon
- List: OEM
- Removal: Advanced
- Description: This package is part of Motorola's custom overlay for Wi-Fi settings and resources. It includes Motorola-specific modifications or enhancements for Wi-Fi management and user interface elements related to Wi-Fi on Motorola devices. Removing this package might affect certain Motorola-specific Wi-Fi features or customizations, potentially leading to changes in how Wi-Fi settings are displayed or managed.

APP 6:
- Package name: com.android.wifi.resources.overlay.WifiResScanCountryCode
- List: AOSP
- Removal: Advanced
- Description: This package is related to Wi-Fi resources and overlays, specifically dealing with country code scanning for Wi-Fi networks. It manages resources that could influence how Wi-Fi scans are handled based on the country code settings. Removing this package might impact the handling of Wi-Fi scanning processes, particularly those affected by regional settings, but it is unlikely to disrupt core Wi-Fi functionality.

APP 7:
- Package name: com.google.android.health.connect.backuprestore
- List: Google
- Removal: Recommended
- Description: This package is related to Google Health Connect and handles the backup and restore functionality for health-related data. Removing this package could impact the ability to back up and restore health data associated with Google Health Connect.

APP 8:
- Package name: com.google.android.healthconnect.controller
- List: Google
- Removal: Recommended
- Description: This package is part of Google Health Connect and is responsible for managing and controlling health-related data interactions. It handles data permissions, syncing, and integration between different health-related apps and services.

APP 9:
- Package name: com.google.android.wifi.dialog
- List: Google
- Removal: Recommended
- Description: This package is associated with the user interface elements related to Wi-Fi management in Android. It handles the dialogs and prompts that appear when managing Wi-Fi connections, such as network selection, Wi-Fi settings, and connectivity prompts. Removing this package might impact the appearance or functionality of Wi-Fi management dialogs, potentially making it harder to interact with Wi-Fi settings or connect to networks.

APP 10:
- Package name: com.google.android.wifi.resources
- List: Google
- Removal: Advanced
- Description: This package contains resources related to Wi-Fi management, including string resources, images, and layout files used in the Wi-Fi settings and user interface. It helps provide the necessary resources for displaying and interacting with Wi-Fi settings in the system UI. Removing this package might affect the appearance or usability of Wi-Fi settings and related features, potentially leading to missing resources or visual inconsistencies in Wi-Fi management interfaces.

APP 11:
- Package name: com.motorola.android.coresettingsext.overlay.avatrn
- List: OEM
- Removal: Expert
- Description: This package is part of Motorola's custom overlay for system settings, specifically tailored for the Motorola Edge 2024 (codename "avatrn"). It includes device-specific settings or customizations that are unique to this model. Removing this package could significantly impact Motorola-specific features and custom settings on the Edge 2024, potentially leading to issues with functionality or user interface elements that are specific to this device model.

APP 12:
- Package name: com.motorola.android.launcher.overlay.motolauncheroverlayna
- List: OEM
- Removal: Advanced
- Description: This package is part of Motorola's custom launcher overlay, specifically tailored for their devices. It likely provides Motorola-specific features or visual customizations for the home screen and app launcher experience. Removing this package may affect the appearance and functionality of the launcher, potentially causing issues with Motorola-specific home screen features or customization options.

APP 13:
- Package name: com.motorola.android.launcher.overlay.retail.global
- List: OEM
- Removal: Advanced
- Description: This package is part of Motorola's custom launcher overlay designed for retail or global versions of their devices. It includes modifications or features tailored for the retail environment or for a global market, potentially affecting the appearance and functionality of the home screen and app launcher. Removing this package might affect how the launcher is configured for retail settings or global customization, which could lead to changes in how the launcher looks or behaves.

APP 14:
- Package name: com.motorola.android.networkstack.overlay.mcc460
- List: OEM
- Removal: Expert
- Description: This package is part of Motorola's custom network stack overlay, specifically related to the network configuration for a particular Mobile Country Code (MCC), in this case, MCC 460 (which corresponds to China). It likely includes settings or modifications for network functionality specific to this region. Removing this package might affect network performance, connectivity, or settings specific to the region, potentially causing issues with cellular connectivity or network features that are tailored for that country.

APP 15:
- Package name: com.motorola.android.networkstack.tethering.overlay.motCommon
- List: OEM
- Removal: Advanced
- Description: This package is part of Motorola's custom overlay for the network stack, specifically related to tethering and hotspot functionalities. It provides Motorola-specific modifications or enhancements for managing tethering and sharing network connections. Removing this package may affect how tethering features are presented or function on Motorola devices, potentially impacting the user experience for mobile hotspot and tethering options.

APP 16:
- Package name: com.motorola.android.overlay.lpptoga
- List: OEM
- Removal: Advanced
- Description: This package is part of Motorola's custom overlay and is likely associated with specific visual or functional enhancements tailored for Motorola devices. While the exact role of "lpptoga" is not immediately clear from the name alone, it generally involves Motorola-specific customizations. Removing this package might impact certain Motorola-specific features, settings, or UI elements, potentially altering the user experience.

APP 17:
- Package name: com.motorola.android.overlay.qcom.common
- List: OEM
- Removal: Advanced
- Description: This package is part of Motorola’s custom overlay and is associated with Qualcomm (Qcom) related functionality or optimizations. It likely includes Motorola-specific modifications or enhancements related to Qualcomm hardware features, such as optimizations for performance, power management, or other hardware-specific functionalities. Removing this package might impact certain Qualcomm-related optimizations or features that are customized for Motorola devices, potentially affecting performance or hardware integration.

APP 18:
- Package name: com.motorola.android.providers.settings.auto_generated_rro_product__
- List: OEM
- Removal: Advanced
- Description: This package is part of Motorola’s custom settings provider, and it likely includes resources or settings related to Motorola-specific customizations. The "auto_generated_rro_product__" suffix indicates that it deals with automatically generated resources for settings related to the Motorola device. Removing this package may affect the display or functionality of Motorola-specific settings or customization options in the system settings.

APP 19:
- Package name: com.motorola.android.providers.settings.overlay.dppcamera
- List: OEM
- Removal: Advanced
- Description: This package is part of Motorola's custom settings overlay, specifically related to settings for the camera application. The "dppcamera" component suggests it handles Motorola-specific settings or configurations for camera features, potentially including custom camera options, enhancements, or UI elements unique to Motorola devices. Removing this package may affect the availability or functionality of Motorola-specific camera settings or features.

APP 20:
- Package name: com.motorola.android.providers.settings.overlay.dppnone
- List: OEM
- Removal: Advanced
- Description: This package is part of Motorola's custom settings overlay, potentially dealing with settings or configurations that are applied when certain features or options are not in use. The "dppnone" suffix suggests it may be related to a default or fallback configuration for settings, possibly indicating a state where no specific custom settings are applied. Removing this package might affect default settings or configurations that Motorola uses when certain features are disabled or not active.

APP 21:
- Package name: com.motorola.android.settings.overlay.global
- List: OEM
- Removal: Advanced
- Description: This package is part of Motorola's custom settings overlay and is designed for global settings that apply across different regions or device configurations. It includes Motorola-specific customizations and enhancements for system settings that are intended to be universally applied to their devices. Removing this package might impact how certain global settings or features are presented or configured, potentially altering the user experience related to system settings

APP 22:
- Package name: com.motorola.android.settings.overlay.lra
- List: OEM
- Removal: Advanced
- Description: This package is part of Motorola’s custom settings overlay, likely related to specific regional or device configurations. The "lra" suffix suggests it could be tailored for a particular locale or device feature set. Removing this package might impact Motorola-specific settings or customizations that are associated with certain features or regions.

APP 23:
- Package name: com.motorola.android.settings.overlay.power.bottom
- List: OEM
- Removal: Advanced
- Description: This package is part of Motorola’s custom settings overlay, specifically related to power management settings. The "power.bottom" designation suggests it might handle aspects of power settings or controls positioned at the bottom of the settings interface or related to power features. Removing this package might affect how certain power-related settings or features are presented or managed on Motorola devices.

APP 24:
- Package name: com.motorola.batterycare
- List: OEM
- Removal: Advanced
- Description: This package is part of Motorola's battery management system, specifically related to features or optimizations for battery care. It includes Motorola-specific tools or settings designed to manage battery health, performance, and efficiency. Removing this package might impact battery-related features such as battery optimization settings, health monitoring, or charging behaviors tailored for Motorola devices.

APP 25:
- Package name: com.motorola.batterycare.overlay
- List: OEM
- Removal: Advanced
- Description: This package is part of Motorola’s custom battery care overlay and is likely responsible for providing Motorola-specific enhancements or visual elements related to battery management. It may include custom settings or UI components designed to improve or modify how battery care features are presented on Motorola devices. Removing this package might affect the appearance or functionality of battery care features and settings, potentially leading to changes in how battery information or optimizations are displayed.

APP 26:
- Package name: com.motorola.batterycare.overlay.appside
- List: OEM
- Removal: Advanced
- Description: This package is part of Motorola's custom battery care overlay and is likely associated with specific enhancements or visual elements related to battery management on the app side of the user interface. It may provide additional battery-related settings, optimizations, or visual cues related to app-specific battery usage or management. Removing this package might affect the presentation or functionality of battery management features related to app usage, potentially leading to changes in how app-specific battery information or optimizations are displayed.

APP 27:
- Package name: com.motorola.camera3.content.ai
- List: OEM
- Removal: Advanced
- Description: This package is related to Motorola's camera application, specifically focusing on AI (artificial intelligence) features. It likely handles AI-driven functionalities or enhancements within the camera app, such as scene recognition, image processing, or other smart features designed to improve camera performance and photo quality. Removing this package might affect the AI capabilities of the camera, potentially leading to a decrease in the effectiveness of features like automatic scene detection or enhanced image processing.

APP 28:
- Package name: com.motorola.imagertuning_u
- List: OEM
- Removal: Advanced
- Description: This package is associated with Motorola’s image tuning features, specifically designed to enhance or adjust image quality settings on Motorola devices. It likely includes tools or settings related to image processing, color adjustments, or other visual optimizations for photos and videos. Removing this package might affect the ability to fine-tune or optimize image quality, potentially impacting features related to image enhancement and visual settings.

APP 29:
- Package name: com.motorola.installer
- List: OEM
- Removal: Advanced
- Description: This package is used by Motorola for managing and installing system updates, custom apps, or other Motorola-specific applications. It likely handles the installation process for software updates or Motorola-specific apps and tools that are pre-installed on the device. Removing this package might affect the ability to install or manage certain Motorola-specific software or updates, potentially causing issues with installing new updates or applications provided by Motorola.

APP 30:
- Package name: com.motorola.mykey
- List: OEM
- Removal: Advanced
- Description: This package is related to Motorola’s "MyKey" feature, which is a tool designed to manage key settings and restrictions for device usage. "MyKey" is often used for parental controls or to limit device functionality based on certain criteria or profiles. Removing this package might affect the ability to use or configure key features and restrictions that are specific to Motorola’s implementation of device management or parental controls.

APP 31:
- Package name: com.motorola.om
- List: OEM
- Removal: Advanced
- Description: The package "com.motorola.om" is associated with Motorola's operational management or device management tools. It likely includes components related to Motorola’s custom management features, which might handle updates, diagnostics, or other management functions specific to Motorola devices. Removing this package could impact Motorola-specific operational or management tools, potentially affecting functions related to system updates, diagnostics, or device management features.

APP 32:
- Package name: com.motorola.securityhubext
- List: OEM
- Removal: Advanced
- Description: This package is related to Motorola's Security Hub, an extension or enhancement for the device’s security features. It likely includes Motorola-specific security tools or settings that provide additional security management, monitoring, or configuration options beyond the standard Android security features. Removing this package might impact security-related functionalities or settings specific to Motorola devices, potentially affecting features such as security monitoring or device protection enhancements.

APP 33:
- Package name: com.motorola.setup.auto_generated_rro_product__
- List: OEM
- Removal: Recommended
- Description: This package is involved in Motorola's setup process, particularly handling automatically generated resources related to the setup of the device. It includes Motorola-specific resources that are used during the initial setup phase. Since this package is primarily needed for the setup process and will be restored after a factory reset, it is not critical for ongoing functionality.

APP 34:
- Package name: com.motorola.setup.overlay.dataenable
- List: OEM
- Removal: Recommended
- Description: This package is used during the Motorola device setup process, specifically for managing or presenting settings related to mobile data. It includes Motorola-specific customizations or UI elements that assist in configuring mobile data during the initial setup. Since it is only needed for the setup process and will be restored upon a factory reset, removing this package will not impact the core functionality of the device.

APP 35:
- Package name: com.oem.euiccpartnerapp.overlay.retca
- List: OEM
- Removal: Advanced
- Description: This package is related to the eUICC (embedded Universal Integrated Circuit Card) partner application, specifically an OEM overlay that deals with eSIM functionality and management. The "retca" suffix suggests it could be tied to a specific regional or carrier customization. It likely includes additional features or user interface elements specific to the management and configuration of eSIMs, provided by Motorola or in collaboration with a carrier. Removing this package might impact eSIM management features, potentially affecting the user experience related to eSIM provisioning and configuration.

### Acknowledgements

- [X] I removed all those packages on my phone. If not, why? Explain in the issue.
- [X] This issue is not a duplicate of an existing one.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by AnonymousWP** [comment]
@Lost-Entrepreneur439 If you can, could you please add them by yourself as a PR? That'd save us a lot of work and is easier to review. Thanks for the extensive issue!

**Comment by Lost-Entrepreneur439** [comment]
> @Lost-Entrepreneur439 If you can, could you please add them by yourself as a PR? That'd save us a lot of work and is easier to review. Thanks for the extensive issue!

I will work on it, however my computers motherboard has failed so I am quite limited in stuff I am able to do as of right now.

**Comment by AnonymousWP** [comment]
> > @Lost-Entrepreneur439 If you can, could you please add them by yourself as a PR? That'd save us a lot of work and is easier to review. Thanks for the extensive issue!
> 
> I will work on it, however my computers motherboard has failed so I am quite limited in stuff I am able to do as of right now.

That'd be great, but good luck with your motherboard. 🙂
