### ISSUE TITLE
pkg(scope): Oneplus 9 Pro, expert debloat, can send SMS but not receive

### ISSUE THREAD

**Issue by SpookySanta** [Universal-Debloater-Alliance/universal-android-debloater-next-generation#604]
### Describe the problem

Have tried with two different SMS apps. Calling works fine.

### Provide logs

[log9pro.txt](https://github.com/user-attachments/files/16880744/log9pro.txt)

### Acknowledgements

- [X] This issue is not a duplicate of an existing one.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by AnonymousWP** [comment]
Why did you (seemingly blindly) uninstall so many advanced packages? Have you read the descriptions?

**Comment by SpookySanta** [comment]
Yes, tought the expert option didn't break anything.

**Comment by AnonymousWP** [comment]
Well, try to re-install everything. Next time, read it properly and read through https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation/wiki/FAQ. Doesn't `expert` sound like it's far from `recommended` though? 😅

**Comment by schbrns** [comment]
Feel free to re-open the issue if you have any questions regarding specific packages that you can identify. Thanks.
