### ISSUE TITLE
pkg(scope): Removing wallpaper services breaks Lock Star

### ISSUE THREAD

**Issue by stepanzak** [Universal-Debloater-Alliance/universal-android-debloater-next-generation#613]
### Describe the problem

Removing com.samsung.android.dynamiclock (Samsung Wallpaper Services) breaks Lock Star app (part of Good Lock) https://apps.samsung.com/appquery/appDetail.as?appId=com.samsung.systemui.lockstar
While it makes sense, it should still be noted in the package summary.

### You have a solution?

Add this information to the package's summary.

### Provide logs

no

### Acknowledgements

- [X] This issue is not a duplicate of an existing one.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by schbrns** [comment]
Correct. 
So does Live Wallpaper Picker.
These are all in my PR.

**Comment by AnonymousWP** [comment]
> Correct. So does Live Wallpaper Picker. These are all in my PR.

If you're fixing this issue by a PR, please link it (look at the right side of this issue, 'Development').

**Comment by AnonymousWP** [comment]
@schbrns Please follow-up on this.

**Comment by schbrns** [comment]
Planned, will close when PR is up.
