### ISSUE TITLE
Bluetooth Breakage.

### ISSUE THREAD

**Issue by RustyElbow** [Universal-Debloater-Alliance/universal-android-debloater-next-generation#615]
### List your packages

"com.samsung.android.knox.app.networkfilter" 

Brakes bluetooth connection, With ONE UI 6.1.1.

### Acknowledgements

- [X] This issue is not a duplicate of an existing one.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by schbrns** [comment]
@RustyElbow With work profile/secure folder? Knox packages shouldn't affect non-containerized settings.

**Comment by Nono-Song** [comment]
Can confirm this issue. 
One UI 6.1.1.

**Comment by Asra05** [comment]
I can also confirm this issue on One UI 6.1.1.

**Comment by TimeBlaster** [comment]
On my S24 Ultra it also breaks the default phone and messages app after updating to One UI 6.1.1.

**Comment by AnonymousWP** [comment]
Thanks for the reports, I'll work on this. I just need to create a PR and have another team member to approve it.

**Comment by AnonymousWP** [comment]
Fixed in https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation/pull/635 2 weeks ago.
