### ISSUE TITLE
pkg(samsung): change 2 packs from `Recommended` to `Advanced`. sm-s901b

### ISSUE THREAD

**Issue by becksy82** [Universal-Debloater-Alliance/universal-android-debloater-next-generation#619]
### List your packages

Hello, i used the recommend list für my samsung samsung sm-s901b. 
the list contains two apps, that should move to advanced list.

- Package name: 
com.samsung.android.app.routines (Routines functionality)
com.sec.android.app.samsungapps (Galaxy Store)

- Description
com.sec.android.app.samsungapps is the samsung app store and can update samsung specific apps, that are not part of recommend list and not available with play store

com.samsung.android.app.routines provides the functionality to create automatic routines. like automatic enegry save mode. i dont know an other app, that can replace these samsung app.

both apps are quite usefull for the standard user. 
both apps should be for every samsung phone in advanced list.

### Acknowledgements

- [ ] I removed all those packages on my phone. If not, why? Explain in the issue.
- [X] This issue is not a duplicate of an existing one.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by schbrns** [comment]
I'd say Expert for Galaxy Store. Advanced sounds good for routines.
