### ISSUE TITLE
bug(theme): `Auto` always `Light` (regression)

### ISSUE THREAD

**Issue by Rudxain** [Universal-Debloater-Alliance/universal-android-debloater-next-generation#627]
### Describe the bug

`dark-light` v`1.1.1` falls-back to `Light` unconditionally

I've been debugging this and I am 100% certain this is a bug in `dark_light::detect`

### Expected behavior

Theme should be detected properly

### You have a solution?

We could downgrade to v`=1.0.0`, until it's fixed upstream

### Operating System

Linux

### Distro version

Debian 13

### Window System + Manager

Wayland + Mutter

### Desktop Environment

GNOME 46

### Provide logs

_Irrelevant_

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by sgse** [comment]
Firstly, thanks for the app. :-)

As it was so difficult to recognize the logo, I made my own. I didn't know about the 'bug' then. 
If you don't include a .png in the .svg like in the second and third one above, then you also get a clear typeface. It is also much smaller in terms of memory requirements.
Original has 15.1 k
~~~
ls | grep uad-ng
.rw-r--r--  65k root 15 Sep 19:55 uad-ng-1.png
.rw-r--r--  20k root 15 Sep 20:27 uad-ng-1.svg
.rw-r--r-- 4,3k root 15 Sep 20:42 uad-ng.svg
~~~
 
It works for me with the SVG on Arch Based Linux.

![grafik](https://github.com/user-attachments/assets/81cb3213-fd66-477d-96bb-ea085fcc58f2)

![2024-09-16_13-45](https://github.com/user-attachments/assets/7eec6648-fbf3-42b1-9394-f0f8f7ead25a)

![2024-09-16_13-43](https://github.com/user-attachments/assets/a6cf0da3-930d-4624-94eb-75be05945b4d)

**Comment by Rudxain** [comment]
@sgse Thank you! but we should talk about it on #629

**Comment by Frigyes06** [comment]
Cannot reproduce on Arch Plasma/kwin with Wayland

**Comment by Frigyes06** [comment]
Wait I might be dumb, what do you mean by fall back to? Can you provide steps to reproduce?

**Comment by Rudxain** [comment]
According to frewsxcv/rust-dark-light#21, the code returns `Light` instead of `Default` when it fails to detect color-scheme. I know it fails on my system, because it always returns `Light` regardless of my GNOME theme
