### ISSUE TITLE
bug(scope): Not working on Windows 10 IoT Enterprise LTSC 2021

### ISSUE THREAD

**Issue by RadyanZ** [Universal-Debloater-Alliance/universal-android-debloater-next-generation#639]
### Describe the bug

It worked just fine on regular windows 10 home. do you guys have any idea about this issue? thanks in advance.

### Expected behavior

That it launches.

### Operating System

Windows

### Distro version

Windows 10 IoT Enterprise LTSC 2021

### Provide logs

Don't have them

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by RadyanZ** [comment]
I tried the opengl one that was mentioned on the homepage, but the only one I could find was an outdated version, but yes that one worked.

**Comment by AnonymousWP** [comment]
Could you please post logs? And if not, please explain why.

**Comment by RadyanZ** [comment]
yes, sorry. I'm new to github. 

PS C:\Users\R\Desktop\platform-tools> 2024-09-20 22:21:23 ERROR [C:\Users\runneradmin/.cargo\registry\src\index.crates.io-6f17d22bba15001f\wgpu-hal-0.19.4\src\vulkan\instance.rs:837] enumerate_adapters: A return array was too small for the result
2024-09-20 22:21:24 ERROR [C:\Users\runneradmin/.cargo\registry\src\index.crates.io-6f17d22bba15001f\wgpu-hal-0.19.4\src\vulkan\instance.rs:837] enumerate_adapters: A return array was too small for the result

**Comment by RadyanZ** [comment]
Nevermind, I fixed it with a new amd driver. Thanks for your time.
