### ISSUE TITLE
bug(scope): Font distorted

### ISSUE THREAD

**Issue by Aman1337g** [Universal-Debloater-Alliance/universal-android-debloater-next-generation#641]
### Describe the bug

I have installed the **uad-ng-linux** v1.1.0 binary file. I am currently using pop-os 22.04. I am giving it the execution persmission by `chmod +x ./uad-ng-linux` , after opening it the font displayed is not undertandable.
![Screenshot from 2024-09-22 21-26-36](https://github.com/user-attachments/assets/40449e02-6f29-45a1-904a-3fdf0ec54e32)

### Expected behavior

The font should be displayed properly to understand what is written.

### Operating System

Linux

### Provide logs

[UAD_20240922.log](https://github.com/user-attachments/files/17090307/UAD_20240922.log)

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by Rudxain** [comment]
Duplicate #523

I'll reopen the old Issue, please let's continue there
