### ISSUE TITLE
feat(search): add possibility to search for descriptions

### ISSUE THREAD

**Issue by Rudxain** [Universal-Debloater-Alliance/universal-android-debloater-next-generation#647]
### Describe the feature you want

- 0x192/universal-android-debloater#134
- #640

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by AnonymousWP** [comment]
This is a duplicate of https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation/issues/184 it seems.
