### ISSUE TITLE
bug(scope): Very slow and laggy UI experience on kali linux .

### ISSUE THREAD

**Issue by StarMusa88** [Universal-Debloater-Alliance/universal-android-debloater-next-generation#662]
### Describe the bug

Very slow and laggy UI experience compared to the original UAD on kali linux .But ubuntu and windows 11 seems fine. just wondering what could be the issue ??.

### Expected behavior

N/A

### You have a solution?

N/A

### Operating System

Linux

### Distro version

Kali Linux, Win 11 , Ubuntu

### Window System + Manager

xorg

### Desktop Environment

Gnome

### Provide logs

<details><summary>Log</summary>

```
Please replace this line by the log-file contents
```
</details>

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by AnonymousWP** [comment]
Which version of UAD-ng?

**Comment by StarMusa88** [comment]
Hi,

version1.1.0

theme=Automatic

https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation/releases/download/v1.1.0/uad-ng-linux

**Comment by AnonymousWP** [comment]
Yes it's a known issue.

**Comment by Rudxain** [comment]
It'll be fixed in the next release. See #650
