### ISSUE TITLE
pkg(scope): com.google.android.apps.messaging breaks sms on Unihertz Titan Pocket

### ISSUE THREAD

**Issue by p1neapple-juice** [Universal-Debloater-Alliance/universal-android-debloater-next-generation#668]
### Describe the problem

Device: Unihertz Titan Pocket
System: Android 11
Messaging App: QKSMS, Fossify SMS, Google Messages

removing package breaks receiving all messages with one special exception. Sending messages works 100% as it should. If I send a message and the recipient responds within 5 minutes, I receive it with no problem. If they take longer than 5 minutes it is lost to the universe.

Reinstalling does not fix the problem. Factory reset fixes it. I ran UAD again and removed all the same packages but left com.google.android.apps.messaging and messaging works as it should.

Also tried 3 different carriers to make sure it wasnt a carrier issue and it is definitely software.

### You have a solution?

add comment to app description warning Unihertz users

### Provide logs

I can upload logfiles if you need me to but that will require me to reset and rebreak the phone. I have the original UAD logfiles now if you want them.

### Acknowledgements

- [X] This issue is not a duplicate of an existing one.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by AnonymousWP** [comment]
Is it ok like this?
