### ISSUE TITLE
pkg(scope): Remove some apps from Recommended list

### ISSUE THREAD

**Issue by ZMJGMADHPXWT** [Universal-Debloater-Alliance/universal-android-debloater-next-generation#687]
### Describe the problem

I've installed PixelMagic (Android 15) custom ROM to my phone recently and decided to debloat it.

Deletion of com.android.cameraextentsions will broke MIUI camera. This camera was integrated by a maintainer to this ROM to make video quality better.
Deletion of com.google.android.apps.nbu.files - will make manual app installation impossible. After that you can install apps only via Google play.
Deletion of  com.google.android.apps.wallpaper - makes theme configuration impossible.

### You have a solution?

Move these apps to Advanced section.

### Provide logs

[UAD_20241006.log](https://github.com/user-attachments/files/17270732/UAD_20241006.log)

### Acknowledgements

- [X] This issue is not a duplicate of an existing one.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by angeluskun** [comment]
well i can delete files by google on global rom and dosent break package installation maybe you should discuss with your rom developer to add android package installer to prevent this

**Comment by angeluskun** [comment]
> > well i can delete files by google on global rom and dosent break package installation maybe you should discuss with your rom developer to add android package installer to prevent this
> 
> Besides that you can describe what you did more precisely. And use punctuation marks. I read it 3 times and understood almost nothing.
> 
> Thanks.

some custom miui roms does not have aosp package installer so thats the problem, ask your developer to add it or use global rom debloated i suggest taiwan rom and you will not have any problem

**Comment by schbrns** [comment]
Out of precedent, we won't be making modifications based on custom ROMs. 
If you can confirm such breakages happen within base MIUI, we can make modifications based on that.

As you said, the maintainer is the one that is maintaining the camera app for their custom ROM. 

And as the other user tried to help you understand 3 times, it is the maintainer's responsibility to ensure their re-implementation of an existing Android feature doesn't break in a way that the OEM/AOSP versions don't.
