### ISSUE TITLE
pkg(com.huawei.lbs): Causing Bootloop on Huawei Matepad 11.5"S Papermatte

### ISSUE THREAD

**Issue by kekuwi** [Universal-Debloater-Alliance/universal-android-debloater-next-generation#690]
### Describe the problem

OS: Harmony OS 4.2.0
Model: Huawei Matepad 11.5"S Papermatte

after removing package & rebooting, device repeatedly rebooting itself after 5-8 seconds

### Provide logs

[UAD_20241014.log](https://github.com/user-attachments/files/17358845/UAD_20241014.log)

### Acknowledgements

- [X] This issue is not a duplicate of an existing one.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by AnonymousWP** [comment]
Which package is responsible? Check the description of each `Recommended` package.
