### ISSUE TITLE
bug(adb): "Adb not installed" error even though the reboot worked

### ISSUE THREAD

**Issue by GingrPowr** [Universal-Debloater-Alliance/universal-android-debloater-next-generation#703]
### Describe the bug

I think that since I didn't installed ADB the way this project wants to (I used it before), after clicking [Reboot] the "ADB not installed on your system" error is displayed. But my connected device still rebooted, because I added my ADB install folder into my PATH environment variables. Worth to mention: it also worked before, to uninstall the 120+ bloatware that were reinstalled on my freshely reseted Samsung J5. So ADB is installed, works (I used it before today), is detected by the app and works with the app.

### Expected behavior

Either:
- Fail and display error message,
- Work and don't display error message.

### You have a solution?

Either:
- Do not use ADB installed in a different manner than what is asked in your installation guideline -> which would be a shame since it's currently working,
- Update the installation guideline, and the app error check, and keep using the ADB found in PATH -> preferred option.

### Operating System

Windows

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by VideoBeeYT** [comment]
I have same issue, it's such a hassle that they didn't think about the simplest thing ever

**Comment by zicke2** [comment]
Download android platform tools and unzip it somewhere.
https://dl.google.com/android/repository/platform-tools-latest-windows.zip

Put the tool into this Folder and start it from there… it will work ;)

greets from austria
![Screenshot 2024-11-12 181316](https://github.com/user-attachments/assets/996e9981-263f-4755-a7ca-453f55319407)

**Comment by GingrPowr** [comment]
> Download android platform tools and unzip it somewhere. https://dl.google.com/android/repository/platform-tools-latest-windows.zip
> 
> Put the tool into this Folder and start it from there… it will work ;)
No, that will not resolve the bug, only hide it.

**Comment by Frigyes06** [comment]
#700 related

**Comment by GingrPowr** [comment]
@Frigyes06 This is not a feature or an enhancement.

This is a bug to be fixed: the software is stating something and doing the inverse, literally working while it says it won't.
Also I don't see how this bug might be linked to issue 700.
