### ISSUE TITLE
removing com.android.carrierdefaultapp breaks data connection on oppo device

### ISSUE THREAD

**Issue by Asra05** [Universal-Debloater-Alliance/universal-android-debloater-next-generation#713]
### You have a solution?

The solution is to reinstall the package to restore mobile data functionality.

### Acknowledgements

- [X] This issue is not a duplicate of an existing one.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by SchneeSchmitt** [comment]
Data still works fine for my OnePlus Ace 3V on ColorOS 14 and 15
Although it's quite normal to see a package breaks something on specific devices

**Comment by schbrns** [comment]
The description already mentions this exact breakage.

Please feel free to re-open the issue if you have any other questions. Thanks.
