### ISSUE TITLE
Add pkg(com.android.permissioncontroller): to debloat list

### ISSUE THREAD

**Issue by SchneeSchmitt** [Universal-Debloater-Alliance/universal-android-debloater-next-generation#715]
### List your packages

- Package name: com.android.permissioncontroller
- List: AOSP
- Removal: Unsafe
- Description:
Important component that allow or disallow app permissions such as camera, microphone and location.
Removing it doesn't cause bootloop.

### Acknowledgements

- [X] I removed all those packages on my phone. If not, why? Explain in the issue.
- [X] This issue is not a duplicate of an existing one.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by schbrns** [comment]
This description already exists.

Please feel free to re-open the issue if you have any questions. Thanks.
