### ISSUE TITLE
bug(scope): Failed to perform ADB operation  [Advanced] pm uninstall-user 0 com.samsung.android.themecenter -> Fallure [DELETE FAILED_INTERNAL_ERROR

### ISSUE THREAD

**Issue by SJ1O** [Universal-Debloater-Alliance/universal-android-debloater-next-generation#723]
### Describe the bug

When trying to uninstall galaxy theme services I get this error. 

Failed to perform ADB operation

[Advanced] pm uninstall-user 0 com.samsung.android.themecenter -> Fallure [DELETE FAILED_INTERNAL_ERROR

### Expected behavior

Item to be uninstalled or disabled?

### Operating System

Windows

### Distro version

Windows 11

### Provide logs

<details><summary>Log</summary>

```
Please replace this line by the log-file contents
```
</details>

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by AnonymousWP** [comment]
It means Samsung doesn't allow you to uninstall the app. Try disabling instead.
