### ISSUE TITLE
bug(scope): When trying to uninstall spay framework  I get this error: Failed to perform ADB operation  [Recommended] pm uninstall-user 0 com.samsung.android.spayfw-> Failure [DELETE_FAILED_OWNER_BLOCKED]

### ISSUE THREAD

**Issue by SJ1O** [Universal-Debloater-Alliance/universal-android-debloater-next-generation#724]
### Describe the bug

When trying to uninstall spay framework I get this error.
Failed to perform ADB operation

[Recommended] pm uninstall-user 0 com.samsung.android.spayfw-> Failure [DELETE_FAILED_OWNER_BLOCKED]

### Expected behavior

Uninstall app

### Operating System

Windows

### Distro version

Windows 11

### Provide logs

<details><summary>Log</summary>

```
Please replace this line by the log-file contents
```
</details>

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by AnonymousWP** [comment]
It means Samsung doesn't allow you to uninstall the app. Try disabling instead.

**Comment by SJ1O** [comment]
Is the only way to disabled on my phone or can I use uadb?

**Comment by AnonymousWP** [comment]
> Is the only way to disabled on my phone or can I use uadb?

You can either use UAD-ng or ADB to disable an app. Sometimes, Samsung allows you to disable the app from the settings of OneUI.

**Comment by SJ1O** [comment]
> > Is the only way to disabled on my phone or can I use uadb?
> 
> You can either use UAD-ng or ADB to disable an app. Sometimes, Samsung allows you to disable the app from the settings of OneUI.

Could you tell me how to disable using uad-ng please. I looked in the settings and cannot find a disabled option only uninstall. I did read the faq but it doesn't explain how to use the disable option.

**Comment by SJ1O** [comment]
> > Is the only way to disabled on my phone or can I use uadb?
> 
> You can either use UAD-ng or ADB to disable an app. Sometimes, Samsung allows you to disable the app from the settings of OneUI.

Nevermind I found the settings to disable apps I wasn't looking very good. Thanks for all your work and app
