### ISSUE TITLE
feat(scope): add click in description

### ISSUE THREAD

**Issue by Foul** [Universal-Debloater-Alliance/universal-android-debloater-next-generation#753]
### Describe the feature you want

Hello, it would be cool to be able to add the fact of clicking on a URL in the description at the bottom.
For now, when you choose a package, the description is displayed at the bottom, and often there is a URL in it... but unfortunately not clickable.

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by AnonymousWP** [comment]
Thanks for the issue, but this is a duplicate: https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation/issues/49
